### PR TITLE
Using separator in code constants

### PR DESCRIPTION
**Pull request by peterennis**
Correction for typos in constant names. NOTE: lunr - http://lunrjs.com -
A bit like Solr, but much smaller and not as bright - 0.6.0
This project has the same problem but it is not touched in the PR.

### CODE REVIEW

**Comment by peterennis** [comment]
PR opened with lunr to fix their source.
https://github.com/olivernn/lunr.js/pull/223/commits/d953667143021f82c5a48fcf28dd8a71f6957898

**Comment by qinezh** [comment]
The angular template is deprecated now, please do not modify it.

**Comment by peterennis** [comment]
OK. I will pull new code at the next release. Is lunr being removed?

**Comment by qinezh** [comment]
No, lunr.js is used for full text search and won't be removed.

**Comment by peterennis** [comment]
Closed as deprecated.

**Comment by peterennis** [comment]
lunr.js
https://github.com/olivernn/lunr.js/pull/223#issuecomment-254634270
separator should be resolved with 0.7.2

**Pull request closed without merging**
