### PR TITLE
Handle AttributeData.AttributeConstructor being null

### PR DESCRIPTION
**Pull request by xen2**

### CODE REVIEW

**Comment by hellosnow** [comment]
:shipit:

**Comment by superyyrrzz** [comment]
:+1: @vwxyzh

**Comment by superyyrrzz** [comment]
Hi @xen, can you give a sample project or minimal repro steps? This fix is OK, while it may cover the root cause of this bug.

**Comment by xen2** [comment]
I have a repro project available on github, but it is quite big, hope that's OK...

```
git lfs clone https://github.com/SiliconStudio/xenko.git -b master-1.6
git clone https://github.com/SiliconStudio/xenko-docs.git
cd xenko-docs
# alternatively run your own compiled docfx with xenko-docs as current folder
deps\docfx\docfx.exe
```

Note that you will need https://github.com/dotnet/docfx/pull/390 as well

**Comment by vwxyzh** [comment]
👍

**Pull request merged**
