### PR TITLE
Add styling for alerts to default theme

### PR DESCRIPTION
**Pull request by pascalberger**
Add styling for alerts to the default theme and improve documentation for DFM notes.

### CODE REVIEW

**Comment by qinezh** [comment]
Thanks your contribution @pascalberger . To make it easy to review, could you provide a demo to show the effect of your PR? Such as a github pages site. You may take the repo [docfx-seed](https://github.com/docascode/docfx-seed.git) as an example.

**Comment by pascalberger** [comment]
@qinezh I already added samples to the DocFx documentation here: https://github.com/dotnet/docfx/pull/959/files#diff-02cb1a68782218b698ac2c3413f853b0R156. 

Do you still need a sample in another place?

**Comment by vicancy** [comment]
Looks pretty cool. Thanks @pascalberger

**Comment by pascalberger** [comment]
@vicancy See also #958 which would give more styling opportunities for the alerts on other stuff by defining the HTML created for the DFM extensions in the theme.

**Pull request merged**
