### PR TITLE
fix metadata incremental check bug

### PR DESCRIPTION
**Pull request by ansyral**
take the following case as an example:
the src contains project A, B C.
1. project A depends on B,
2. project C depends on B, E
3. project E depends on A.

the original code might omit the dependency relationship 3 and generate the topological order BCA, which is wrong.

### CODE REVIEW

**Comment by ansyral** [comment]
#507

**Comment by vwxyzh** [comment]
✔️

**Comment by hellosnow** [comment]
:shipit:

**Comment by qinezh** [comment]
:100:

**Pull request merged**
