### PR TITLE
support implements for event/property, fix generic implements

### PR DESCRIPTION
**Pull request by superyyrrzz**
@vwxyzh @ansyral @chenkennt @qinezh @hellosnow

### CODE REVIEW

**Comment by vwxyzh** [comment]
👍

**Comment by ansyral** [comment]
LGTM👍

**Comment by ansyral** [comment]
@superyyrrzz seems implements broke when there are method generic  parameters

**Comment by superyyrrzz** [comment]
@ansyral Yes, I don't include the template change in this commit to avoid merge conflict. Will add another commit to fix this.

**Pull request merged**
