### PR TITLE
Add ResolveSourceRelativePath as common template utility function

### PR DESCRIPTION
**Pull request by qinezh**
@chenkennt @vwxyzh @superyyrrzz @ansyral 

Sample to use `ResolveSourceRelativePath` in template:

```javascript
model.breadcrumb_path = templateUtility.resolveSourceRelativePath(model.breadcrumb_path, model._path);
```

### CODE REVIEW

**Comment by vwxyzh** [comment]
> ```js
> var model.breadcrumb_path = templateUtility.ResolveSourceRelativePath(model.breadcrumb_path, model._path);
> ```

prefer camel case for js method.

**Comment by superyyrrzz** [comment]
:shipit:

**Comment by hellosnow** [comment]
:shipit:

**Comment by vwxyzh** [comment]
:shipit:

**Pull request merged**
