### PR TITLE
filter out info level in vscode validation extension

### PR DESCRIPTION
**Pull request by shanluo911**
[AB#566595](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/566595)

### CODE REVIEW

**Review by herohua — APPROVED** [review]

**Review by yufeih — CHANGES_REQUESTED** [review]
It feels wrong to suppress all info level traces to fix a single inaccurate error code.

**Comment by 928PJY** [comment]
> It feels wrong to suppress all info level traces to fix a single inaccurate error code.

The **Info** trace is still logged in the output channel, we just don't convert it into diagnostic, which will be displayed when the user hover, it is noisy to convert all info into disagnostic.

**Comment by 928PJY** [comment]
There is a configuration called "trace-level", we should be able to leverage that to control the trace level, but for this fix, it looks good to me.

**Review by yufeih — APPROVED** [review]
Looks good for info

**Pull request merged**
