### PR TITLE
Improves the default template for TypeScript documentation

### PR DESCRIPTION
**Pull request by rbuckton**
This PR makes a few changes to the default template to fix some issues and better support TypeScript documentation. This PR is also intended to align with the changes to the `@microsoft/api-documenter` package in https://github.com/microsoft/web-build-tools/pull/1537.

- Add TypeScript namespaces, type aliases, and exported variables to the default template: 
image
- Fixes Inheritance hierarchy rendering: 
image
- Adds entries for the current TypeScript namespace (if one was recorded), and the containing package: 
image

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/docfx/pull/5128)

### CODE REVIEW

**Comment by octogonz** [comment]
Awesome, thanks for making this PR!  We've been waiting for this DocFX improvement for a long time.

**Comment by octogonz** [comment]
@alexjerabek FYI

**Comment by octogonz** [comment]
@dend @OsmondJiang @yufeih  

I noticed the `v2` tag.  Just curious, what's the usual timeframe for releasing a template update?

For some context, DocFX's handling of TypeScript namespaces has been an issue for libraries like Office Add-ins and Office UI Fabric for a long time.  This PR is the second-to-last in a series of PRs that @rbuckton has been working on over the summer, which should finally solve this problem.  We're really excited about it!  But we can't merge https://github.com/microsoft/web-build-tools/pull/1537 until the fixed template has been released.

**Comment by octogonz** [comment]
> you mentioned this is the second-to-last PR, once all the PRs are merged, we can release an update of docfx. Release train ships every 3 weeks or so.

The other PRs aren't for the DocFX project.  They are for [API Extractor](https://api-extractor.com/), which is the tool that Office uses to generate the .yml input files for DocFX.  The last PR https://github.com/microsoft/web-build-tools/pull/1537 will update API Extractor to generate .yml files for namespaces, which requires the updated template from this PR.  (Thus it is blocked until this PR gets merged+released.)  Sorry, I guess I could have explained that better.  😊

**Comment by yufeih** [comment]
@octogonz that make sense.

**Comment by rbuckton** [comment]
@yufeih Does the DocFX project publish nightly builds?

**Comment by yufeih** [comment]
yep, here is the feed: https://www.myget.org/feed/Packages/docfx-dev

**Pull request merged**
