### PR TITLE
implememts dependency in dfm.

### PR DESCRIPTION
**Pull request by vwxyzh**
@chenkennt @superyyrrzz @hellosnow @ansyral @qinezh 
#449

### CODE REVIEW

**Comment by superyyrrzz** [comment]
:shipit:

**Comment by qinezh** [comment]
:shipit:

**Comment by hellosnow** [comment]
>         public static void ReportDependency(this IMarkdownContext context, string file)

could reuse the overload method below?

---
Refers to: src/Microsoft.DocAsCode.Dfm/DfmContextExtensions.cs:63 in 3d4fe64. [](commit_id = 3d4fe64452ceef48a112f4e0684b021610b27e6b, deletion_comment = False)

**Comment by hellosnow** [comment]
:shipit:

**Pull request merged**
