### PR TITLE
Update to latest FSharp.Compiler.Service

### PR DESCRIPTION
**Pull request by smindinvern**
- There don't appear to be any changes in FCS API semantics, only changes to names (and removal of the `Microsoft.` namespace prefix), so this was a straightforward edit.
- FCS factored some dependencies out into a new `FSharp.Compiler.Service.MSBuild.v12.0` package which is hosted on a `myget` feed, so this feed needed to be added to the `NuGet.Config` file.

#3679

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/docfx/pull/5637)

### CODE REVIEW

**Comment by superyyrrzz** [comment]
A test failed. @smindinvern could you help fix it? https://docfx.visualstudio.com/docfx/_build/results?buildId=1297&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=bd05475d-acb5-5619-3ccb-c46842dbc997&l=8925

**Comment by smindinvern** [comment]
@superyyrrzz: Done!  For some reason binding redirects for `Microsoft.Build.*` assemblies weren't being auto-generated, so the unit test suite was binding to an old version.  🤷‍♂

**Comment by superyyrrzz** [comment]
Thank you for contribution!

**Comment by superyyrrzz** [comment]
@smindinvern Now `FSharp.Compiler.Service.MSBuild.v12.0` is missed in the myget feed, so our CI is failing when restore. Do you have idea how to fix it? /cc @v-pegao 

https://github.com/fsharp/FSharp.Compiler.Service/issues/961

**Comment by smindinvern** [comment]
@superyyrrzz: Sorry for the super-long delay.

Unfortunately, it looks like the myget feed has been entirely removed.  fsharp/FSharp.Compiler.Service#958 seems to suggest that the packages have been moved [here](https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json), but querying that endpoint returns only beta versions of FCS, and no `FSharp.Compiler.Service.MSBuild.v12.0`.

I suppose we could nicely ask that the packages be reinstated, but barring that the only option would be to update to a more recent version of FCS.

**Comment by v-pegao** [comment]
@smindinvern Thanks for the response! 

Since the latest fsharp msdn package still references the missing dependency package. we had opened an issue([#fsharp/FSharp.Compiler.Service#961](https://github.com/fsharp/FSharp.Compiler.Service/issues/961)) to ask them to reinstate the package or provide a working feed.

To unblock the coming docfx releasement, we decided to revert [this commit](https://github.com/dotnet/docfx/pull/5637/files) temporarily until the issue resolved.

cc @superyyrrzz

**Pull request merged**
