### PR TITLE
fix specName not encoded

### PR DESCRIPTION
**Pull request by superyyrrzz**

### CODE REVIEW

**Comment by hellosnow** [comment]
>                 result += " altProperty=\"fullName\"";

need fullName encoded?

---
Refers to: src/Microsoft.DocAsCode.Build.ManagedReference/BuildOutputs/ApiBuildOutputUtility.cs:105 in c2f6a58. [](commit_id = c2f6a580a5f25fd9b878a3f11e186ab855869a34, deletion_comment = False)

**Comment by superyyrrzz** [comment]
>                 result += " altProperty=\"fullName\"";

no need, it's a property name

---
In reply to: [287262650](https://github.com/dotnet/docfx/pull/1434#issuecomment-287262650) [](ancestors = 287262650)

---
Refers to: src/Microsoft.DocAsCode.Build.ManagedReference/BuildOutputs/ApiBuildOutputUtility.cs:105 in c2f6a58. [](commit_id = c2f6a580a5f25fd9b878a3f11e186ab855869a34, deletion_comment = False)

**Comment by hellosnow** [comment]
>                 result += " altProperty=\"fullName\"";

yes I misunderstood it

---
In reply to: [287268245](https://github.com/dotnet/docfx/pull/1434#issuecomment-287268245) [](ancestors = 287268245,287262650)

---
Refers to: src/Microsoft.DocAsCode.Build.ManagedReference/BuildOutputs/ApiBuildOutputUtility.cs:105 in c2f6a58. [](commit_id = c2f6a580a5f25fd9b878a3f11e186ab855869a34, deletion_comment = False)

**Comment by hellosnow** [comment]
:shipit:

**Pull request merged**
