### PR TITLE
upgrade doc.validation

### PR DESCRIPTION
**Pull request by cuiyun01**
[AB#294553](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/294553)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/docfx/pull/6525)

### CODE REVIEW

**Review by OsmondJiang — APPROVED** [review]

**Review by OsmondJiang — COMMENTED** [review]
I am thinking we probable should not change the message related to the toc node validation, @fkpwolf @cuiyun01

**Review by OsmondJiang — APPROVED** [review]

**Comment by fkpwolf** [comment]
the diff is excepted. @yufeih pls check and merge.

**Pull request merged**
