### PR TITLE
[V3] Add documents of included TOCs into dependent list file but not build them

### PR DESCRIPTION
**Pull request by byszhoubin**
Work item 115868: https://dev.azure.com/ceapex/Engineering/_workitems/edit/115868

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/docfx/pull/5195)

### CODE REVIEW

**Comment by fenxu** [comment]
test needed

**Comment by mingwli** [comment]
off-line verifed with @byszhoubin, take below inputs for example:

```yaml
inputs:
  docfx.yml:
  docs/TOC.md: |
    # [Reference TOC File 1](f1/TOC.md)
  docs/f1/TOC.md: |
    # [Index Reference](index.md)
  docs/f1/index.md:
```

```
{"dependency_type":"metadata","from_file_path":"D:\\workspace\\docfx-related\\docfx\\test\\docfx.Test\\bin\\Debug\\netcoreapp2.2\\docfx-test\\toc.yml-09-04aeede2\\inputs\\docs\\f1\\index.md","to_file_path":"D:\\workspace\\docfx-related\\docfx\\test\\docfx.Test\\bin\\Debug\\netcoreapp2.2\\docfx-test\\toc.yml-09-04aeede2\\inputs\\docs\\TOC.md"}
{"dependency_type":"file","from_file_path":"D:\\workspace\\docfx-related\\docfx\\test\\docfx.Test\\bin\\Debug\\netcoreapp2.2\\docfx-test\\toc.yml-09-04aeede2\\inputs\\docs\\f1\\TOC.md","to_file_path":"D:\\workspace\\docfx-related\\docfx\\test\\docfx.Test\\bin\\Debug\\netcoreapp2.2\\docfx-test\\toc.yml-09-04aeede2\\inputs\\docs\\f1\\index.md"}
{"dependency_type":"include","from_file_path":"D:\\workspace\\docfx-related\\docfx\\test\\docfx.Test\\bin\\Debug\\netcoreapp2.2\\docfx-test\\toc.yml-09-04aeede2\\inputs\\docs\\TOC.md","to_file_path":"D:\\workspace\\docfx-related\\docfx\\test\\docfx.Test\\bin\\Debug\\netcoreapp2.2\\docfx-test\\toc.yml-09-04aeede2\\inputs\\docs\\f1\\TOC.md"}
``` 

all expected dependencies are already reported:  
  * parent toc -> child toc   : include
  * child toc -> article.md    : file
  * article.md -> parent toc : metadata(_tocRel)

And the changes in this pr **WILL** influence _tocRel priorities.

It's better to re-check pr comment logic. @fenxu is there simple ways for testing PR comment behavior with mock-up data?

**Comment by herohua** [comment]
@byszhoubin @fenxu per my understanding, this PR is no longer needed. shall we abandon this PR?

**Comment by byszhoubin** [comment]
> @byszhoubin @fenxu per my understanding, this PR is no longer needed. shall we abandon this PR?

Yes, we can. I've cloed this PR

**Pull request closed without merging**
