### PR TITLE
redirect wkhtmltopdf stderr to avoid fail docfx

### LINKED ISSUE #4488: PDF Build fails in Azure DevOps
**Operation System**: Windows

**DocFX Version Used**: DocFx Build Tasks - [Visual Studio Marketplace Extension](https://marketplace.visualstudio.com/items?itemName=chrismason.vsts-docfxtasks)

**Template used**: pdf.default

**Additional Information**: I am able to create the PDF locally just not in a build pipeline in Azure DevOps.

**Steps to Reproduce**:
1. Get Sources from repository
2. Add Chocolatey task to Install wkhtmltopdf
3. Run Create DocFx task to create PDF
4. Project File "docfx_pdf.json"  <-- Just testing PDF build.  Content builds work correctly.
```
"pdf": {
        "content": [
            {
                "files": [
                    "**/*.md",
                    "**/**.yml"
                ],
                "exclude": [
                    "**/toc.yml",
                    "**/toc.md"
                ]
            },
            {
                "files": "pdf/toc.yml"
            }
        ],
        "resource": [
            {
                "files": [
                    "**/*.png",
                    "**/*.jpg",
                    "**/*.gif",
                    "**/*.pdf",
                    "**/*.pptx",
                    "favicon.ico"
                ],
                "exclude": [
                    "**/obj/**",
                    "**/includes/**",
                    "**/_site_pdf/**"
                ]
            }
        ],
        "overwrite": [],
        "dest": "_site_pdf"
    }
```

**Expected Behavior**:
Create PDF file

**Actual Behavior**:
PDF file is not create with these errors in the Build Pipeline.

```
[19-05-06 06:59:08.197]Error:[PdfCommand.PDF]Error happen when converting pdf/toc.json to Pdf. Details: System.InvalidOperationException: The file is not a valid PDF document.
   at PdfSharp.Pdf.IO.PdfReader.Open(Stream stream, String password, PdfDocumentOpenMode openmode, PdfPasswordProvider passwordProvider)
   at Microsoft.DocAsCode.HtmlToPdf.HtmlToPdfConverter.SaveCore(Stream stream)
   at Microsoft.DocAsCode.HtmlToPdf.HtmlToPdfConverter.Save(String outputFileName)
   at Microsoft.DocAsCode.HtmlToPdf.ConvertWrapper.<>c__DisplayClass7_0.<ConvertCore>b__1(ManifestItem tocFile)
	24 Warning(s)
	1 Error(s)
##[error]Unable to run command: d:\a\1\s\docfx_pdf.json
code: 1

[19-05-06 06:58:57.112]Info:[PdfCommand.BuildCore.Build Document.LinkPhaseHandlerWithIncremental.Apply Templates]Applying templates to 1029 model(s)...
[19-05-06 06:58:57.707]Info:[PdfCommand.BuildCore.Build Document]XRef map exported.
[19-05-06 06:58:58.568]Info:[PdfCommand.Postprocess]Manifest file saved to manifest.json.
[19-05-06 06:58:58.661]Info:[PdfCommand]Completed building documents in 7219.7605 milliseconds.
[19-05-06 06:58:58.661]Info:[PdfCommand.PDF]Start generating PDF files...
[19-05-06 06:59:08.009]Error:[PdfCommand.PDF]Error happen when converting pdf/toc.json to Pdf. Details: System.InvalidOperationException: The file is not a valid PDF document.
   at PdfSharp.Pdf.IO.PdfReader.Open(Stream stream, String password, PdfDocumentOpenMode openmode, PdfPasswordProvider passwordProvider)
   at Microsoft.DocAsCode.HtmlToPdf.HtmlToPdfConverter.SaveCore(Stream stream)
   at Microsoft.DocAsCode.HtmlToPdf.HtmlToPdfConverter.Save(String outputFileName)
   at Microsoft.DocAsCode.HtmlToPdf.ConvertWrapper.<>c__DisplayClass7_0.<ConvertCore>b__1(ManifestItem tocFile)
[19-05-06 06:59:08.197]Info:[PdfCommand.PDF]Completed Scope:PdfCommand.PDF in 9530.6019 milliseconds.
[19-05-06 06:59:08.197]Info:[PdfCommand]Completed Scope:PdfCommand in 17068.4582 milliseconds.
[19-05-06 06:59:08.197]Info:Completed in 17073.8428 milliseconds

Build failed.

[19-05-06 06:59:08.197]Error:[PdfCommand.PDF]Error happen when converting pdf/toc.json to Pdf. Details: System.InvalidOperationException: The file is not a valid PDF document.
   at PdfSharp.Pdf.IO.PdfReader.Open(Stream stream, String password, PdfDocumentOpenMode openmode, PdfPasswordProvider passwordProvider)
   at Microsoft.DocAsCode.HtmlToPdf.HtmlToPdfConverter.SaveCore(Stream stream)
   at Microsoft.DocAsCode.HtmlToPdf.HtmlToPdfConverter.Save(String outputFileName)
   at Microsoft.DocAsCode.HtmlToPdf.ConvertWrapper.<>c__DisplayClass7_0.<ConvertCore>b__1(ManifestItem tocFile)
	24 Warning(s)
	1 Error(s)

stderr: QFont::setPixelSize: Pixel size <= 0 (0)

error: undefined
```

### PR DESCRIPTION
**Pull request by superyyrrzz**
This is an alternative of #4719 to fix #4488.

When using `wkhtmltopdf`, we need to pass a bunch of HTML file names to it. There are 2 ways: through arguments or through stdin. Arguments can work in most cases but sometimes will fail when the repo has many articles that make the arguments exceed the max length limitation. So by default we choose stdin with  `--read-args-from-stdin`.

This PR will redirect `wkhtmltopdf`'s stderr to avoid break docfx. Usually the info in stderr is not fatal error that needn't terminate docfx.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/docfx/pull/4733)

### CODE REVIEW

**Comment by oleksabor** [comment]
I've tested locally and on the Azure pipeline
Locally it works fine (but there is no error generated)
In the Azure build it fails

> [19-06-13 10:41:11.444]Verbose:[PDF.wkhtmltopdf]Executing wkhtmltopdf  --javascript-delay 3000 -q --no-outline --encoding utf-8 --user-style-sheet "defaults/default-css.css" --read-args-from-stdin ("E:/buildagent/network/_work/12/s/docfx_project/_site_pdf/_raw/_site_pdf/pdf/TOC.html" -)
> [19-06-13 10:41:12.005]Verbose:[PDF.wkhtmltopdf]Executing wkhtmltopdf  --javascript-delay 3000 -q --no-outline --encoding utf-8 --user-style-sheet "defaults/default-css.css" --read-args-from-stdin ("E:/buildagent/network/_work/12/s/docfx_project/_site_pdf/_raw/_site_pdf/pdf/../articles/xml.samples.html" -)
> [19-06-13 10:41:12.978]Verbose:[PDF.wkhtmltopdf]Executing wkhtmltopdf  --javascript-delay 3000 -q --no-outline --encoding utf-8 --user-style-sheet "defaults/default-css.css" --read-args-from-stdin ("E:/buildagent/network/_work/12/s/docfx_project/_site_pdf/_raw/_site_pdf/pdf/../articles/export.sample.html" -)
> [19-06-13 10:41:13.792]Verbose:[PDF.wkhtmltopdf]got wkhtmltopdf output 0Bytes
> [19-06-13 10:41:13.792]Verbose:[PDF.wkhtmltopdf]got exitCode 1 for ( --javascript-delay 3000 -q --no-outline --encoding utf-8 --user-style-sheet "defaults/default-css.css" --read-args-from-stdin)
> Convert the file : "E:/buildagent/network/_work/12/s/docfx_project/_site_pdf/_raw/_site_pdf/pdf/../index.html" - has exception, the details: Cannot read from a closed TextReader.
> [19-06-13 10:41:13.823]Verbose:[PDF.wkhtmltopdf]got wkhtmltopdf output 0Bytes
> [19-06-13 10:41:13.823]Verbose:[PDF.wkhtmltopdf]got wkhtmltopdf output 0Bytes
> [19-06-13 10:41:13.823]Verbose:[PDF.wkhtmltopdf]got exitCode 1 for ( --javascript-delay 3000 -q --no-outline --encoding utf-8 --user-style-sheet "defaults/default-css.css" --read-args-from-stdin)
> [19-06-13 10:41:13.823]Verbose:[PDF.wkhtmltopdf]got exitCode 1 for ( --javascript-delay 3000 -q --no-outline --encoding utf-8 --user-style-sheet "defaults/default-css.css" --read-args-from-stdin)
> Convert the file : "E:/buildagent/network/_work/12/s/docfx_project/_site_pdf/_raw/_site_pdf/pdf/../articles/service.https.html" - has exception, the details: Cannot read from a closed TextReader.


please note that 

- there is no output as before `got wkhtmltopdf output 0Bytes`
- `Cannot read from a closed TextReader.` is raised since stream is closed when process exits.

I've tried to move read from stderr before `WaitForExit` but it freezes when running locally, probably because of this https://stackoverflow.com/questions/139593/processstartinfo-hanging-on-waitforexit-why

I've tried to replace stderr read with  `process.BeginErrorReadLine();` and `process.ErrorDataReceived += (sender, e) =>` according to the SO answer but the same `got wkhtmltopdf output 0Bytes` in the log for Azure build.

**Comment by oleksabor** [comment]
> Arguments can work in most cases but sometimes will fail when the repo has many articles that make the arguments exceed the max length limitation.

probably it may happen but I see that every html file is executed with separate wkhtmltopdf process start:

> [19-06-13 10:35:53.370]Verbose:[PDF.wkhtmltopdf]Executing wkhtmltopdf  --javascript-delay 3000 -q --no-outline --encoding utf-8 --user-style-sheet "defaults/default-css.css" --read-args-from-stdin ("D:/work/DirectClientDataSync/docfx_project/_site_pdf/_raw/_site_pdf/pdf/../articles/service.setup.html" -)
> [19-06-13 10:35:53.374]Verbose:[PDF.wkhtmltopdf]Executing wkhtmltopdf  --javascript-delay 3000 -q --no-outline --encoding utf-8 --user-style-sheet "defaults/default-css.css" --read-args-from-stdin ("D:/work/DirectClientDataSync/docfx_project/_site_pdf/_raw/_site_pdf/pdf/TOC.html" -)
> [19-06-13 10:35:53.376]Verbose:[PDF.wkhtmltopdf]Executing wkhtmltopdf  --javascript-delay 3000 -q --no-outline --encoding utf-8 --user-style-sheet "defaults/default-css.css" --read-args-from-stdin ("D:/work/DirectClientDataSync/docfx_project/_site_pdf/_raw/_site_pdf/pdf/../index.html" -)

**Comment by superyyrrzz** [comment]
@oleksabor Just want to confirm whether you are using this PR to test? From the log message, which I see arguments is wrapped with parenthesis. This looks like some [changes from your PR](https://github.com/dotnet/docfx/pull/4719/files#diff-1ef960f6413a10a7f915d7a86595b869R139).

> [19-06-13 10:41:11.444]Verbose:[PDF.wkhtmltopdf]Executing wkhtmltopdf --javascript-delay 3000 -q --no-outline --encoding utf-8 --user-style-sheet "defaults/default-css.css" --read-args-from-stdin ("E:/buildagent/network/_work/12/s/docfx_project/_site_pdf/_raw/_site_pdf/pdf/TOC.html" -)

**Comment by oleksabor** [comment]
Actually I've merged changed lines from yours PR to the source code that I
have locally. And argument logging was not updated since my changes

**Comment by superyyrrzz** [comment]
@oleksabor Got it. Looks like we can rely on #4719 to fix this.

BTW, I am thinking of adding some test for this. Actually our PR check runs on Azure Pipeline. It should be easy to reproduce this issue.

**Pull request closed without merging**
