### PR TITLE
Update to template, as per docs bug # 549692

### PR DESCRIPTION
**Pull request by DuncanmaMSFT**
“Introduction” doesn’t seem like a very good term to use – it doesn’t really make clear what the content is. “Summary Description” might be better.  - Suggestion - Move it above inheritance and remove the need for title 'Introduction'

### CODE REVIEW

**Comment by mairaw** [comment]
We have made a similar request before to address this. /cc @sankethka

**Comment by superyyrrzz** [comment]
:+1: LGTM

**Comment by sankethka** [comment]
@mairaw That same item has been assigned to Duncan. Duncan owns this item now.

**Comment by mairaw** [comment]
Ah, cool! Glad to see this coming along then. :smile:

**Pull request merged**
