### PR TITLE
Abort upon load source model error

### PR DESCRIPTION
**Pull request by mingwli**
[DevOps#178055](https://dev.azure.com/ceapex/Engineering/_workitems/edit/178055)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/docfx/pull/5544)

### CODE REVIEW

**Comment by mingwli** [comment]
> ⚠[DevSandbox](https://github.com/OPS-E2E-PPE/DevSandbox)(00:00:20.2889324, 0 more diff)



> ⚠[DevSandbox](https://github.com/OPS-E2E-PPE/DevSandbox)(00:00:20.2889324, 0 more diff)

@yufeih @fenxu  does this break publish-on-error ?

**Comment by yufeih** [comment]
What is the cause of `DevSandbox` diff, I don't think it is expected

**Comment by mingwli** [comment]
> What is the cause of `DevSandbox` diff, I don't think it is expected

The build page returns before adding to PublishModelBuilder.
https://github.com/mingwli/docfx/blob/load-abort/src/docfx/build/page/BuildPage.cs#L55

**Comment by mingwli** [comment]
Track .publish.json issue in [DevOps#178143](https://ceapex.visualstudio.com/Engineering/_queries/edit/178143/?triage=true)

**Pull request merged**
