### PR TITLE
Fix invalid `moniker-range-undefined` error on included file

### PR DESCRIPTION
**Pull request by 928PJY**
[AB#376315](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/376315)

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/docfx/pull/7066)

### CODE REVIEW

**Review by yufeih — APPROVED** [review]
💯

**Comment by 928PJY** [comment]
@yufeih https://github.com/microsoft/azure-cseries-preview this repository used in our spec test has been locked, so the test fails

**Comment by yufeih** [comment]
@928PJY can you help review the diff and see if they are expected?

**Comment by 928PJY** [comment]
@yufeih confirmed, all the diffs are expected.

**Pull request merged**
