### PR TITLE
Remove unused publish output

### PR DESCRIPTION
**Pull request by yufeih**
Now that we've switched to the new publish pipeline, these output are no longer needed:

- *.mta.json
- *.raw.page.json --> *.json
- output in .manifest.json
- output_relative_path in .manifest.json

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/docfx/pull/5043)

### CODE REVIEW

**Comment by OsmondJiang** [comment]
This will have impacts to migration process, we need a detail steps to retire old publish system, like changes in migration tool, how to compare v2 output(old publish pipeline) with v3 output(new publish pipeline)?

**Comment by yufeih** [comment]
> This will have impacts to migration process, we need a detail steps to retire old publish system, like changes in migration tool, how to compare v2 output(old publish pipeline) with v3 output(new publish pipeline)?

There will be a corresponding PR in migration tool. Meanwhile the old publish system has already been retired in docfx v3 @fenxu

**Comment by yufeih** [comment]
Migration tool changes https://apidrop.visualstudio.com/Content%20CI/_git/docfx-v3-migration/pullrequest/616?_a=overview

**Comment by yufeih** [comment]
This PR currently has some dependencies on migration tool, so I cannot be done at the moment. @928PJY #4450

**Pull request closed without merging**
