### PR TITLE
Add properties to video extension

### PR DESCRIPTION
**Pull request by jamarw**
Add support for thumbnail, upload-date, duration and description (still clarifying requirements).

[AB#261869](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/261869)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/docfx/pull/6318)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/docfx?pullRequest=6318) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docfx?pullRequest=6318) before we can accept your contribution.<br/><br/>:x: jamarw [sign now](https://cla.dotnetfoundation.org/dotnet/docfx?pullRequest=6318)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docfx?pullRequest=6318) it.</sub>

**Comment by yufeih** [comment]
@jamarw The failed test case shows build output change due to source content change and it is safe to merge. 👍

**Pull request merged**
