### PR TITLE
chore: Refactor docfx command related code

### PR DESCRIPTION
**Pull request by filzrev**
**What's included in this PR**
- ~~Change docfx command related API/Models from internal to public.~~

- ~~Remove `<InternalsVisibleTo Include="docfx" />` settings~~
- Move constant string `docfx.json` definition to `Docfx.DataContracts.Common` project.
- Add `RunMetadata.cs` wrapper to use `DotnetApiCatalog` API.

**Background**
As described at #8872.
Current `Docfx.App` package expose limited API set only.
By this PR, `Docfx.App` user can consume same APIs that is used by `docfx.exe`.

### CODE REVIEW

**Comment by yufeih** [comment]
Thanks for putting this together. I need some time to examine the public API surface and may likely tweak it a little bit.

**Comment by yufeih** [comment]
Here are some of the public API guidelines for the config objects I have in mind:
1. The C# property name should match the JSON config name, we could enforce it by applying `[JsonObject(NamingStrategyType = typeof(CamelCaseNamingStrategy))]` at the class level. We also don't seem to need the `[Serializable]` attributes.
2. Internalize all obsolete properties
3. Make the config object immutable so we don't need to make defensive copies or verify mutability:
    * Use `init` over `set`
    * Use `ImmutableArray<T>` over `List<T>` or `T[]`
    * Use `ImmutableDictionary<TKey, TValue>` over `Dictionary<TKey, TValue>`
4. For types that allows both short-hand and expanded forms, expose only the expanded form with a custom JSON converter applied at property level:
    * `ListWithStringFallback` -> `ImmutableArray<string>`
    * `FileMetadataPairs` -> `ImmutableDictionary<string, object>`
    * `FileItems` -> `ImmutableArray<string>`
    * `FileMapping` -> `ImmutableArray<FileMappingItem>`

**Comment by filzrev** [comment]
Thank you for your explanations about public API guidelines.
But `3.` and `4.` requires additional codes and it seems hard to maintenance.

So I decided to to use `IgnoresAccessChecksToGenerator` to ignore internal modifier on my code.
And modify this PR with following changes only.
- Move constant string docfx.json definition to Docfx.DataContracts.Common project.
- Add RunMetadata.cs wrapper to use DotnetApiCatalog API.

**Review by yufeih — APPROVED** [review]
Thank you @filzrev

**Pull request merged**
