### PR TITLE
Replacing null context from build handlers

### PR DESCRIPTION
**Pull request by CodeBeast357**
Correction of System.NullReferenceException from Microsoft.DocAsCode.Build.Engine.LinkPhaseHandler.ExportManifest

### CODE REVIEW

**Comment by lextm** [comment]
Just hit such an exception,
```
[17-12-10 10:42:04.625]Error:System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DocAsCode.Build.Engine.LinkPhaseHandler.<>c__DisplayClass17_0.<ExportManifest>b__0(FileModel m)
   at Microsoft.DocAsCode.Plugins.DocumentExceptionExtensions.RunAll[TElement](IReadOnlyList`1 elements, Action`1 action)
   at Microsoft.DocAsCode.Build.Engine.LinkPhaseHandler.ExportManifest(HostService hostService)
   at Microsoft.DocAsCode.Build.Engine.LinkPhaseHandler.Save(List`1 hostServices, Int32 maxParallelism)
   at Microsoft.DocAsCode.Build.Engine.LinkPhaseHandler.Handle(List`1 hostServices, Int32 maxParallelism)
   at Microsoft.DocAsCode.Build.Engine.PhaseProcessor.Process(List`1 hostServices, Int32 maxParallelism)
   at Microsoft.DocAsCode.Build.Engine.SingleDocumentBuilder.Build(IDocumentProcessor processor, DocumentBuildParameters parameters, IMarkdownService markdownService)
   at Microsoft.DocAsCode.SubCommands.MetadataMerger.MergePageViewModel(MetadataMergeParameters parameters)
   at Microsoft.DocAsCode.SubCommands.MetadataMerger.Merge(MetadataMergeParameters parameters)
   at Microsoft.DocAsCode.SubCommands.MergeCommand.MergeDocument(String baseDirectory, String outputDirectory)
```
Sounds like this patch is not released as part of 2.28.2, which is strange.

The patch was made 17 days ago, while 2.28.2 shipped 4 days ago.

**Comment by CodeBeast357** [comment]
The merge didn't stick as it is missing from the history. I recreated the branch pending another merge.

**Comment by vicancy** [comment]
oops, @CodeBeast357 sorry that I didn't notice that you were targeting `master` branch, `master` branch was overwritten by `dev` branch when we release new version

**Comment by vicancy** [comment]
@CodeBeast357 Could you reopen one targeting `dev` branch?

**Comment by lextm** [comment]
@CodeBeast357 but this PR alone is almost useless, as the second parameter is still `null` for `LinkPhaseHandler`'s constructor, which leads to other crashes. I will create an issue to track all the problems I found regarding the "merge" operation.

**Pull request merged**
