### PR TITLE
Update log message for log code 'circular-reference'

### PR DESCRIPTION
**Pull request by v-pegao**
|log code|changes|
|---|---|
|circular-reference|message|

### CODE REVIEW

**Comment by yufeih** [comment]
@v-pegao would you also change the message for v2 in another PR?

**Comment by v-pegao** [comment]
@yufeih The PR for updating circular-reference in v2: [4593](https://github.com/dotnet/docfx/pull/4593)

**Comment by yufeih** [comment]
@v-pegao , can you help upgrade markdig extensions to the latest and incorporate the changes in #4593 ?

**Comment by v-pegao** [comment]
@yufeih, PR to upgrade markdig extensions: [4622](https://github.com/dotnet/docfx/pull/4622)

**Pull request merged**
