### PR TITLE
Update TripleColonParser.cs for zone correct closed

### PR DESCRIPTION
**Pull request by v-caxian**
**Related Work:** [User Story 44737: Markdig parser DCR to enable zone end validation](https://ceapex.visualstudio.com/Engineering/_workitems/edit/44737)

**Root cause:** The `SelfClosing` has only the default value of false, which causes the value of the `Closed` to always be true.

### CODE REVIEW

**Comment by v-caxian** [comment]
@jeahyoun @yishengjin1413

**Comment by v-caxian** [comment]
@yufeih, done

**Comment by v-caxian** [comment]
Hi @yufeih, 

Actually, I don't have write access to this repository, do you know who can help me merge the pull request?
After the pull request merged, when is the next deployment?

**Comment by yufeih** [comment]
I'll merge it once @yishengjin1413 is ok with this. It'll then be deployed to PPE the next day.

**Pull request merged**
