### PR TITLE
Add net461 build target for common libararies

### PR DESCRIPTION
**Pull request by vicancy**
Fix https://github.com/dotnet/docfx/issues/2358. As with netstandard libarary referenced, new version of *System.Runtime.InteropServices.RuntimeInformation* is introduced by build system with no way to turn around

### CODE REVIEW

**Comment by tzachshabtay** [comment]
Hi @vicancy , can you explain the fix? 
I have the same "MSBuildNameIgnoreCaseComparer" exception in my own application (unrelated to DocFX), and I'm trying to understand the issue and the fix, but nothing in your changes seem to actually mention "System.Runtime.InteropServices.RuntimeInformation".
How is adding net461 solves the problem?

**Comment by vicancy** [comment]
Hi @tzachshabtay, in our case, it is that when net461 project A.csproj references netstandard2.0 project B.csproj, msbuild uses a newer version of `System.Runtime.InteropServices.RuntimeInformation` inside netcore2.0 sdk even if I specify a lower version in my A.csproj because this assembly is a MUST have assembly for netstandard project. Looks like this newer version of `System.Runtime.InteropServices.RuntimeInformation` is not supported by Mono, so as a workaround, I uses net461 all the way down.

**Comment by tzachshabtay** [comment]
Thanks for the explanation @vicancy , is there an issue on Mono for this? Is this the issue? https://github.com/mono/mono/issues/7011

**Comment by vicancy** [comment]
@tzachshabtay yes that is! didn't find that one before, thanks for pointing that out.

**Comment by vicancy** [comment]
Are you meeting the same issue @tzachshabtay ? does the workaround apply for you?

**Comment by tzachshabtay** [comment]
@vicancy yes, I'm pretty sure I'm meeting the same issue. I haven't tried the workaround. As mono supposedly fixed the issue I think I'm going to wait for a version with the fix and try that first.

**Pull request merged**
