### PR TITLE
Dev task229732: [MyGet] update feeds to new locations (DocFX v3)

### PR DESCRIPTION
**Pull request by byszhoubin**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/docfx/pull/6003)

### CODE REVIEW

**Comment by byszhoubin** [comment]
The build error message:
Unable to load the service index for source https://pkgs.dev.azure.com/ceapex/_packaging/OpenPublishingService/nuget/v3/index.json.

Response status code does not indicate success: 401 (Unauthorized)

Looks like docfx v3 can't get package from OpenPublishingService feed.

@herohua Please help confirm if this is permission issue or other issue.

**Comment by yufeih** [comment]
@byszhoubin as an open source project, docfx cannot depend on private NuGet feed. If you fetch the latest v3 branch, there is no `op-external` dependency now.

**Comment by byszhoubin** [comment]
If there is no package dependent on op-external, I'll remove this feed from config

**Comment by byszhoubin** [comment]
I removed op-external from Nuget.config, the build failed of error message:

Unable to find package Microsoft.Docs.LocaleHelper
Unable to find package Microsoft.Docs.MetadataService.Models

For package Microsoft.Docs.LocaleHelper, it's existing in OpenPublishingService feed.
For package Microsoft.Docs.MetadataService.Models, it doesn't exist in OpenPublishingService feed, I think this one still in op-external feed.

Given docfx v3 can't depend on private feed, @herohua  please help confirm if we need to move these 2 packages to public feed?

cc: @yufeih

**Comment by yufeih** [comment]
I can see these are transitive dependencies from `Validation.DocFXAdapter`. We should be able to decouple them.

**Comment by herohua** [comment]
@yufeih Any good suggestion? I am thinking to put those packages into `docs-public-packages`.

**Comment by byszhoubin** [comment]
I just moved All versions of these 2 packages into docs-public-packages feed.

Link: 
[Microsoft.Docs.LocaleHelper](https://docfx.visualstudio.com/docfx/_packaging?_a=package&feed=docs-public-packages&package=Microsoft.Docs.LocaleHelper&protocolType=NuGet&version=2.0.19211.1)

[Microsoft.Docs.MetadataService.Models](https://docfx.visualstudio.com/docfx/_packaging?_a=package&feed=docs-public-packages&package=Microsoft.Docs.MetadataService.Models&protocolType=NuGet&version=0.3.6)

cc: @herohua @yufeih

**Pull request merged**
