### PR TITLE
refactor templates

### PR DESCRIPTION
**Pull request by superyyrrzz**
@chenkennt @herohua @vwxyzh @hellosnow @ansyral @qinezh 

1. refact templates in DocFX
  * `common`: shared by all templates, embedded in `docfx.exe`
  * `op.common`: shared by all templates in OP (*TODO: move to OP*)
  * `op.mta.common`: shared by templates that need `.mta.json` in OP, like `docs.html`, `op.html` (*TODO: move to OP*)
  * Other templates in DocFX remain the same.
2. *TODO: add templates to OP*
  * move `op.common`, `op.mta.common`, `op.html`, `docs.html`, `msdn.html`, `vs.html`
3. *TODO: remove OP related templated in DocFX*

### CODE REVIEW

**Comment by vwxyzh** [comment]
👍

**Comment by hellosnow** [comment]
:shipit:

**Comment by qinezh** [comment]
:dog:

**Comment by herohua** [comment]
:panda_face:

**Pull request merged**
