### PR TITLE
remove siteBasePath from routes and always prepend to sitePath

### PR DESCRIPTION
**Pull request by 928PJY**
#4222 

require changes of config migration tool @mingwli :
1. remove `siteBasePath` from routes

### CODE REVIEW

**Comment by 928PJY** [comment]
just need to update impact repo config

**Comment by yufeih** [comment]
> Depending on the migration tool change

I see, we might need a flow to handle breaking changes

**Comment by yufeih** [comment]
Stupid /azp, you cannot run with a custom parameter

**Comment by OsmondJiang** [comment]
image
this seems wired for me

**Comment by yufeih** [comment]
@928PJY , need to create and reopen a PR using a different branch name 😭

**Pull request closed without merging**
