### PR TITLE
Add reserved metadata cmProducts

### PR DESCRIPTION
**Pull request by yifanbian-msft**
[AB#579783](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/579783)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/docfx?pullRequest=7965) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docfx?pullRequest=7965) before we can accept your contribution.<br/><br/>:x: yifanbian-msft [sign now](https://cla.dotnetfoundation.org/dotnet/docfx?pullRequest=7965)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docfx?pullRequest=7965) it.</sub>

**Review by yufeih — APPROVED** [review]

**Comment by herohua** [comment]
I don't think this PR is necessary as build time produced metadata won't include `cmProducts`. @yifanbian-msft Is the idea to keep consistent with other page metadata produced by build?

**Comment by yifanbian-msft** [comment]
@herohua No, this change is to prevent user from specifying this metadata value and got data mixed up with our data.

**Comment by herohua** [comment]
<details><summary>🧭<a href='https://github.com/MicrosoftDocs/azure-docs-pr'>azure-docs-pr</a>(00:01:46.9841516 | exceed 100s, 8093MB)</summary>

```diff
diff --git "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/azure/active-directory-b2c/conditional-access-technical-profile.raw.page.json" "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/azure/active-directory-b2c/conditional-access-technical-profile.raw.page.json"
index 08bc65d..d786425 100644
--- "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/azure/active-directory-b2c/conditional-access-technical-profile.raw.page.json"
+++ "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/azure/active-directory-b2c/conditional-access-technical-profile.raw.page.json"
@@ -238,7 +238,7 @@
         {
           "name": "felickz",
           "profile_url": "https://github.com/felickz",
-          "display_name": "Chad",
+          "display_name": "Chad Bentz",
           "id": "1760475"
         },
         {


``````csharp
 27% | docfx!Microsoft.Docs.Build.ParallelUtility+<>c__DisplayClass2_0`1[System.__Canon].<ForEach>b__0(!0)
 23% | docfx!Microsoft.Docs.Build.DocsetBuilder+<>c__DisplayClass41_1.<Build>b__15(class Microsoft.Docs.Build.FilePath)
 20% | docfx!Microsoft.Docs.Build.PageBuilder.Build(class Microsoft.Docs.Build.ErrorBuilder,class Microsoft.Docs.Build.FilePath)
 18% | Microsoft.Docs.MarkdigExtensions!Microsoft.Docs.MarkdigExtensions.ResolveLinkExtension.UpdateLinks(class Markdig.Syntax.MarkdownObject)
 15% | docfx!Microsoft.Docs.Build.PageBuilder.LoadMarkdown(class Microsoft.Docs.Build.ErrorBuilder,class Microsoft.Docs.Build.FilePath)
 13% | docfx!Microsoft.Docs.Build.MarkdownEngine.ToHtml(class Microsoft.Docs.Build.ErrorBuilder,class System.String,class Microsoft.Docs.Build.SourceInfo,value class Microsoft.Docs.Build.MarkdownPipelineType,class Microsoft.Docs.Build.ConceptualModel,bool)
 12% | Markdig!Markdig.Markdown.ToHtml(class System.String,class Markdig.MarkdownPipeline)
  9% | Markdig!Markdig.Parsers.MarkdownParser.Parse()
  8% | docfx!Microsoft.Docs.Build.MarkdigUtility.<Replace>g__ReplaceCore|7_0(class Markdig.Syntax.MarkdownObject,class System.Func`2<class Markdig.Syntax.MarkdownObject,class Markdig.Syntax.MarkdownObject>)
  8% | Markdig!Markdig.Renderers.RendererBase.Write(class Markdig.Syntax.MarkdownObject)
  6% | docfx!Microsoft.Docs.Build.Docfx+<>c__DisplayClass6_0.<CreateCommand>b__0(class Microsoft.Docs.Build.CommandLineOptions)
  6% | docfx!Microsoft.Docs.Build.Docfx+<>c__DisplayClass4_0.<BuildCommand>b__0(class Microsoft.Docs.Build.CommandLineOptions)
  6% | docfx!Microsoft.Docs.Build.Builder.Run(class Microsoft.Docs.Build.CommandLineOptions,class Microsoft.Docs.Build.Package)
  5% | docfx!Microsoft.Docs.Build.Builder.Build(class Microsoft.Docs.Build.ErrorBuilder,class System.IProgress`1<class System.String>,class System.String[])
  3% | docfx!Microsoft.Docs.Build.MarkdownEngine.GetLink(class Microsoft.Docs.Build.LinkInfo)
  3% | docfx!Microsoft.Docs.Build.LinkResolver.ResolveLink(value class Microsoft.Docs.Build.SourceInfo`1<class System.String>,class Microsoft.Docs.Build.FilePath,class Microsoft.Docs.Build.FilePath,class Microsoft.Docs.Validation.LinkNode,class System.String)
  3% | docfx!Microsoft.Docs.Build.PageBuilder.CreatePageOutput(class Microsoft.Docs.Build.ErrorBuilder,class Microsoft.Docs.Build.FilePath,class Newtonsoft.Json.Linq.JObject)
  3% | docfx!Microsoft.Docs.Build.Builder+<>c__DisplayClass8_0.<Build>b__0(class Microsoft.Docs.Build.DocsetBuilder)
  3% | Markdig!Markdig.Renderers.RendererBase.WriteChildren(class Markdig.Syntax.ContainerBlock)
  3% | docfx!Microsoft.Docs.Build.DocsetBuilder.Build(class System.String[])
  3% | docfx!Microsoft.Docs.Build.MarkdigUtility.Visit(class Markdig.Syntax.MarkdownObject,class System.Func`2<class Markdig.Syntax.MarkdownObject,bool>)
  3% | docfx!Microsoft.Docs.Build.ParallelUtility.ForEach(class Microsoft.Docs.Build.LogScope,class Microsoft.Docs.Build.ErrorBuilder,class System.Collections.Generic.IEnumerable`1<!!0>,class System.Action`1<!!0>)
  3% | docfx!Microsoft.Docs.Build.MarkdownEngine.GetImageLink(class System.String,class Markdig.Syntax.MarkdownObject,class System.String,class System.String)
  3% | docfx!Microsoft.Docs.Build.LinkResolver.TryResolveAbsoluteLink(value class Microsoft.Docs.Build.SourceInfo`1<class System.String>,class Microsoft.Docs.Build.FilePath,class Microsoft.Docs.Build.FilePath,class Microsoft.Docs.Validation.LinkNode,class System.String)
  3% | docfx!Microsoft.Docs.Build.Watch`1[System.__Canon].get_Value()
  2% | docfx!Microsoft.Docs.Build.ErrorBuilder.AddRange(class System.Collections.Generic.IEnumerable`1<class Microsoft.Docs.Build.Error>)
  2% | docfx!Microsoft.Docs.Build.ContentValidator.ValidateLink(class Microsoft.Docs.Build.FilePath,class Microsoft.Docs.Validation.LinkNode)
  2% | Markdig!Markdig.Renderers.TextRendererBase.Render(class Markdig.Syntax.MarkdownObject)
  2% | docfx!Microsoft.Docs.Build.ErrorLog.Add(class Microsoft.Docs.Build.Error)
  2% | docfx!Microsoft.Docs.Build.PageBuilder.CreateSystemMetadata(class Microsoft.Docs.Build.ErrorBuilder,class Microsoft.Docs.Build.FilePath,class Microsoft.Docs.Build.UserMetadata)

```

</details>

**Comment by herohua** [comment]
<details><summary>🧭<a href='https://github.com/MicrosoftDocs/dynamics365-docs-odata-apis'>dynamics365-docs-odata-apis</a>(00:00:20.9930511 | exceed 20s, 4630MB)</summary>



</details>

**Comment by herohua** [comment]
<details><summary>⚠<a href='https://github.com/MicrosoftDocs/azure-devops-docs-pr'>azure-devops-docs-pr</a>(00:00:13.4825361, 2784 more diff, 769MB)</summary>

```diff
diff --git "a/D:/docfx.TestData\\regression-test.azure-devops-docs-pr\\output/docs/.publish.json" "b/D:/docfx.TestData\\regression-test.azure-devops-docs-pr\\.temp/docs/.publish.json"
index 5e17c9e..c9d72ff 100644
--- "a/D:/docfx.TestData\\regression-test.azure-devops-docs-pr\\output/docs/.publish.json"
+++ "b/D:/docfx.TestData\\regression-test.azure-devops-docs-pr\\.temp/docs/.publish.json"
@@ -103651,7 +103651,7 @@
         "KathrynEE",
         "LizCasey1",
         "damabe",
-        "v-rajagt",
+        "v-rajagt-zz",
         "ShannonLeavitt",
         "jameshkramer",
         "v-thepet",
@@ -103771,7 +103771,7 @@
       "github_contributors": [
         "KathrynEE",
         "damabe",
-        "v-rajagt",
+        "v-rajagt-zz",
         "mijacobs",
         "chcomley",
         "steved0x"
@@ -104127,7 +104127,7 @@
       "github_contributors": [
         "KathrynEE",
         "v-chmccl",
-        "v-rajagt",
+        "v-rajagt-zz",
         "damabe",
         "DCtheGeek",
         "v-thepet",
@@ -108231,7 +108231,7 @@
         "steved0x",
         "GitHubber17",
         "chcomley",
-        "v-rajagt",
+        "v-rajagt-zz",
         "smholvoet",
         "v-hearya",
         "KathrynEE",
@@ -108302,7 +108302,7 @@
         "damabe",
         "PRMerger9",
         "juliakm",
-        "v-rajagt",
+        "v-rajagt-zz",
         "ramiMSFT",
         "john-par",
         "mijacobs",
@@ -114346,7 +114346,7 @@
       "document_version_independent_id": "9df241f4-209c-7c50-9a67-9e87d0094003",
       "github_contributors": [
         "KathrynEE",
-        "v-rajagt",
+        "v-rajagt-zz",
         "v-hearya",
         "mijacobs",
         "chcomley",
@@ -114405,7 +114405,7 @@
       "document_version_independent_id": "dad68e5a-3891-c715-a197-e335474aa39d",
       "github_contributors": [
         "KathrynEE",
-        "v-rajagt",
+        "v-rajagt-zz",
         "v-hearya",
         "mijacobs",
         "chcomley",
@@ -115846,7 +115846,7 @@
         "KathrynEE",
         "JPGRodrigues",
         "damabe",
-        "v-rajagt",
+        "v-rajagt-zz",
         "denrea",
         "DCtheGeek",
         "v-thepet",
@@ -116915,7 +116915,7 @@
         "KathrynEE",
         "chcomley",
         "v-kents",
-        "v-rajagt",
+        "v-rajagt-zz",
         "DCtheGeek",
         "atikmapari",
         "Anduin2017",
@@ -117030,7 +117030,7 @@
       "document_version_independent_id": "4b62e000-81d7-ccf7-0566-e43dd27af3f2",
       "github_contributors": [
         "KathrynEE",
-        "v-rajagt",
+        "v-rajagt-zz",
         "DCtheGeek",
         "chcomley",
         "mijacobs",
@@ -117697,7 +117697,7 @@
       "document_version_independent_id": "464756d2-43d6-2475-4825-e0477c9fb56f",
       "github_contributors": [
         "KathrynEE",
-        "v-rajagt",
+        "v-rajagt-zz",
         "rikat-ms",
         "netchkin",
         "chcomley",
@@ -120243,7 +120243,7 @@
         "Ja-Dunn",
         "ramrajesh",
         "DCtheGeek",
-        "v-rajagt",
+        "v-rajagt-zz",
         "v-hearya",
         "Jominana",
         "ktoliver",
@@ -129275,7 +129275,7 @@
         "KathrynEE",
         "damabe",
         "v-chmccl",
-        "v-rajagt",
+        "v-rajagt-zz",
         "DCtheGeek",
         "mijacobs",
         "chasewilson",
@@ -130124,7 +130124,7 @@
       "document_version_independent_id": "5cd4964c-4b3e-4002-4bcd-945ae9465543",
       "github_contributors": [
         "KathrynEE",
-        "v-rajagt",
+        "v-rajagt-zz",
         "carlosmorgado",
         "chcomley",
         "DCtheGeek",
@@ -130595,7 +130595,7 @@
         "TimShererWithAquent",
         "steved0x",
         "silviuandrica",
-        "v-rajagt",
+        "v-rajagt-zz",
         "v-andreaco",
         "juliakm",
         "ktoliver",
@@ -138596,7 +138596,7 @@
       "document_version_independent_id": "68fecc49-f5bb-00f1-c1d7-4fd50ced9c38",
       "github_contributors": [
         "KathrynEE",
-        "v-rajagt",
+        "v-rajagt-zz",
         "PRMerger16",
         "DCtheGeek",
         "v-thepet",
@@ -141835,7 +141835,7 @@
         "KathrynEE",
         "steved0x",
         "atikmapari",
-        "v-rajagt",
+        "v-rajagt-zz",
         "mijacobs",
         "chcomley"
       ],
@@ -143207,7 +143207,7 @@
         "ramiMSFT",
         "steved0x",
         "smholvoet",
-        "v-rajagt",
+        "v-rajagt-zz",
         "shadargee1982"
       ],
       "updated_at": "2022-02-24 12:19 AM",
@@ -145045,7 +145045,7 @@
       "document_version_independent_id": "2b438da7-0ea1-51da-38b4-168f864ae20e",
       "github_contributors": [
         "steved0x",
-        "v-rajagt",
+        "v-rajagt-zz",
         "ramiMSFT",
         "GitHubber17",
         "DCtheGeek",
@@ -145744,7 +145744,7 @@
         "KathrynEE",
         "damabe",
         "v-hearya",
-        "v-rajagt",
+        "v-rajagt-zz",
         "v-thepet",
         "mijacobs",
         "chasewilson",
@@ -147281,7 +147281,7 @@
         "KathrynEE",
         "smholvoet",
         "chcomley",
-        "v-rajagt",
+        "v-rajagt-zz",
         "atikmapari",
         "DCtheGeek",
         "v-hearya",
@@ -150412,7 +150412,7 @@
       "document_version_independent_id": "ebb883bd-3f10-213b-52b0-4d0332185d82",
       "github_contributors": [
         "steved0x",
-        "v-rajagt",
+        "v-rajagt-zz",
         "chcomley"


```

</details>

**Comment by herohua** [comment]
<details><summary>🧭<a href='https://github.com/MicrosoftDocs/learn-pr'>learn-pr</a>(00:01:40.9545365 | exceed 100s, 6586MB)</summary>



</details>

**Pull request merged**
