### PR TITLE
support headers h1, h2, h3, and h4 in modern template as in default t…

### PR DESCRIPTION
**Pull request by fabianmabasf**
Build "In this article" sidebar based on h1 headlines(as in default template). Add anchors also for h1 headlines.

### CODE REVIEW

**Comment by yufeih** [comment]
Docfx inherits the [heading SEO guideline](https://learn.microsoft.com/en-us/contribute/content/seo-reference#main-heading-h1) for MSLearn, which recommends H1 as the main heading and H1-H3 as subheading. 

Does this guideline make sense to follow?

(If so, we may want to remove h4 instead of adding h1)

**Comment by fabianmabasf** [comment]
@yufeih: Thanks for sharing your thoughts. In my opinion does the change not conflicts with the mentioned SEO Reference. 
Within the default template (not modern) the behavior is the same: Her will be also H1 added within the sidebar.
As a workaround, we are overwriting the docfx.js witin our custom template.

**Comment by yufeih** [comment]
@fabianmabasf - if this customization is desirable, we could expose a customization option in [main.js](https://github.com/dotnet/docfx/blob/main/templates/modern/src/options.d.ts#L25) and default to `['h2', 'h3', 'h4']`:


```ts
export type DocfxOptions = {
  inThisArticle?: {
    headings?: ('h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6')[]
  }
}
```

```js
/* file: my-template/public/main.js */
export default {
  inThisArticle: {
    headings: ['h1', 'h2', 'h3', 'h4']
  }
}
```

**Comment by fabianmabasf** [comment]
> @fabianmabasf - if this customization is desirable, we could expose a customization option in [main.js](https://github.com/dotnet/docfx/blob/main/templates/modern/src/options.d.ts#L25) and default to `['h2', 'h3', 'h4']`:
> 
> ```ts
> export type DocfxOptions = {
>   inThisArticle?: {
>     headings?: ('h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6')[]
>   }
> }
> ```
> 
> ```js
> /* file: my-template/public/main.js */
> export default {
>   inThisArticle: {
>     headings: ['h1', 'h2', 'h3', 'h4']
>   }
> }
> ```

Hi @yufeih ! It would be greate if you could implement such an option to overwrite the standard behavior. If you want, you can reject this pullrequest.

**Comment by yufeih** [comment]
Closing as this is a breaking change.

**Pull request closed without merging**
