### PR TITLE
remove incorrect h1 line number

### PR DESCRIPTION
**Pull request by OsmondJiang**
[AB#193572](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/193572)

### CODE REVIEW

**Comment by live1206** [comment]
@OsmondJiang The line info of `invalid-code` seems changing randomly, see [this](https://github.com/dotnet/docfx/pull/5681#issuecomment-604325565), the diff was gone after a rerun. Any idea since it is from validation?

**Comment by OsmondJiang** [comment]
> @OsmondJiang The line info of `invalid-code` seems changing randomly, see [this](https://github.com/dotnet/docfx/pull/5681#issuecomment-604325565), the diff was gone after a rerun. Any idea since it is from validation?

I am not really familiar with this `invalid-code` validation, add @hejingkan2005

**Comment by herohua** [comment]
@live1206 @OsmondJiang `invalid-code` is from Markdig extension code sample `code`

**Comment by hejingkan2005** [comment]
> > @OsmondJiang The line info of `invalid-code` seems changing randomly, see [this](https://github.com/dotnet/docfx/pull/5681#issuecomment-604325565), the diff was gone after a rerun. Any idea since it is from validation?
> 
> I am not really familiar with this `invalid-code` validation, add @hejingkan2005
@live1206, from the message, "Invalid code on line 74. Could not find snippet id 'Snippet2'. Make sure your snippet is in your source file.", we don't such rule 'invalid-code' in validation library, is it  build self validation code? // CC @OsmondJiang

**Comment by herohua** [comment]
> > > @OsmondJiang The line info of `invalid-code` seems changing randomly, see [this](https://github.com/dotnet/docfx/pull/5681#issuecomment-604325565), the diff was gone after a rerun. Any idea since it is from validation?
> > 
> > 
> > I am not really familiar with this `invalid-code` validation, add @hejingkan2005
> > @live1206, from the message, "Invalid code on line 74. Could not find snippet id 'Snippet2'. Make sure your snippet is in your source file.", we don't such rule 'invalid-code' in validation library, is it  build self validation code? // CC @OsmondJiang

See my comment here: https://github.com/dotnet/docfx/pull/5684#issuecomment-604782238

**Pull request merged**
