### PR TITLE
fixes metadata generation

### LINKED ISSUE #8097: After Visual Studio update - docfx does not work anymore :-(
**Operating System**: `Windows 11 Pro`

**DocFX Version Used**: docfx 2.59.1.0

**Template used**: `statictoc`

**Steps to Reproduce**:

Latest VS update (today) Microsoft Visual Studio Community 2022 (64-bit) - Version 17.2.6

docfx:

Build succeeded with warning.
[22-07-13 12:35:02.625]Warning:[MetadataCommand.ExtractMetadata](C:/Users/cohle/Desktop/RationalNumerics/System.Numerics.Rational/System.Numerics.Rational.csproj)Workspace failed with: [Failure] Msbuild failed when processing the file 'C:\Users\cohle\Desktop\RationalNumerics\System.Numerics.Rational\System.Numerics.Rational.csproj' with message: Methode nicht gefunden: "System.ReadOnlySpan`1<Char> Microsoft.IO.Path.GetFileName(System.ReadOnlySpan`1<Char>)".
[22-07-13 12:35:02.628]Warning:[MetadataCommand.ExtractMetadata]Project 'C:\Users\cohle\Desktop\RationalNumerics\System.Numerics.Rational\System.Numerics.Rational.csproj' does not contain any documents.
[22-07-13 12:35:02.629]Warning:[MetadataCommand.ExtractMetadata]No metadata is generated for System.Numerics.Rational.
        3 Warning(s)
        0 Error(s)

For project - URL: [https://github.com/c-ohle/RationalNumerics
](https://github.com/c-ohle/RationalNumerics)

Any quick workaround?

### PR DESCRIPTION
**Pull request by tibel**
Fixes #8097

The reason was an update to System.Memory in MSBuild
https://github.com/dotnet/msbuild/pull/7680

### CODE REVIEW

**Review by curt-w — APPROVED** [review]

**Comment by tibel** [comment]
@superyyrrzz Could you help with this, please.

**Comment by saipramod** [comment]
As I understand it, this was due to a `preview` version of msbuild and this affects more than just docfx. Should we not wait for the fix to msbuild as opposed to making changes to docfx or are these changes long overdue ?

**Comment by tibel** [comment]
@saipramod The change in MSBuild was released with Visual Studio 2022 17.2.6

**Comment by saipramod** [comment]
> Visual Studio 2022 17.2.6



> @saipramod The change in MSBuild was released with Visual Studio 2022 17.2.6

does this help - https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-v17.2#17.2.7 ?

**Comment by superyyrrzz** [comment]
The change looks good to me. VS17.3 has been released (https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes). The confusion might be that 17.3 was still preview when this issue was originally raised.

**Review by superyyrrzz — APPROVED** [review]

**Comment by tig** [comment]
This issue is not fixed in VS2022 17.4.0 Preview 1.0:

image

Not sure why the MSBuild shows 17.3.0 when running 17.4.0 Preview 1.0...

I'm installing Visual Studio 2022 version 17.3.1 (not Preview) now. Will report back.

**Comment by OskarKlintrot** [comment]
@tig I assume you need to wait for a new release of DocFX to be released.

**Comment by ibruynin** [comment]
> @tig I assume you need to wait for a new release of DocFX to be released. 

Hi all

Is there any idea when this would roll out in an official 2.x release? Trying to build the dev branch manually now - but that's not trivial so it seems.

Thanks!

**Comment by ibruynin** [comment]
@glopesdev I managed to build the dev branch yesterday

Added "-skipTests" in the build.cmd file
```
@ECHO OFF
PUSHD %~dp0
pwsh -NoProfile -ExecutionPolicy Bypass -Command ".\build.ps1 -skipTests %*; exit $LastExitCode;"
POPD
```

you need VS2019, nuget, npm, pwsh (and maybe more I already forgot)

Afterwards you can copy paste `docfx-dev\target\Release\docfx` to your build machine

As a temp fix I marked that version in an alias to be used for now in the build definition files:

```
# this is our compiled version
Set-Alias -Name docfx -Value C:\tools\docfx\docfx.exe
```

**Comment by glopesdev** [comment]
@ibruynin thanks, it's good to know there is a way to reproduce the build.

Unfortunately, we use a GitHub Actions workflow that uses chocolatey to download docfx into the docker image, so it would still require quite a bit of hand-tweaked reworking of scripts to get something like this going.

**Comment by ibruynin** [comment]
@glopesdev tweaking the docker image might be a solution in that case

Copy the dev branch build in /app/docfx as part of the docker build

And then execute /app/docfx/docfx instead

**Comment by ibruynin** [comment]
@KalleOlaviNiemitalo confirmed. We have builds that don't do api doc generation and those work fine.

Even the one that does (try) api doc generation works well too, only the toc entry says "TO BE REPLACED" and that part of the generated website is useless.

**Comment by OskarKlintrot** [comment]
They just released [v2.59.4](https://github.com/dotnet/docfx/releases/tag/v2.59.4) which seems to work. I ran into all the C# 10 issues so I resorted back to generate from .dll's though.

**Pull request merged**
