### PR TITLE
Updated Validations.DocFx.Adapter to 1.2.24-beta006

### PR DESCRIPTION
**Pull request by bharney0**
[AB#204091](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/204091)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/docfx/pull/5812)

### CODE REVIEW

**Comment by yufeih** [comment]
@bharney0 there are extra warnings in the output on existing repos, can you confirm they are expected?

**Comment by bharney0** [comment]
@yufeih  I'll look through these output warnings. it appears that there are some un-handled cases.

I dont have access to OPS-E2E-PPE organization for some of these repos. How do I get access?

**Comment by yufeih** [comment]
@herohua , would you help grant @bharney0 access to `OPS_E2E_PPE` ?

**Comment by herohua** [comment]
> bharney0

@bharney0 - invited.

@yufeih - also made you owner of OPS_E2E_PPE org.

**Comment by bharney0** [comment]
@yufeih it looks like these diffs are expected. I looked through the examples and they should throw the error for h1-not-first validation rule. This PR should be ready to merge.

**Comment by bharney0** [comment]
@yufeih I checked the output and the diffs looks OK. Please merge when ready.

**Pull request merged**
