### PR TITLE
remove sxs logic from docfx

### PR DESCRIPTION
**Pull request by byszhoubin**

### CODE REVIEW

**Comment by yufeih** [comment]
Amazing! We'll probably need to remove some YAML test cases as well.

**Comment by yufeih** [comment]
Seems like some tests are still failing

**Comment by byszhoubin** [comment]
Fixing test failures

**Review by yufeih — APPROVED** [review]

**Comment by herohua** [comment]
There are a lot of diff's in regression tests too. Please consult @live1206 and @AngryBerryMS before merging the PR.

**Comment by byszhoubin** [comment]
> 

This is expected diff

**Comment by byszhoubin** [comment]
Ping @live1206 @AngryBerryMS

**Comment by 928PJY** [comment]
@byszhoubin please pull the latest v3 branch, you will get rid of the ruleset diff on loc repo
image

**Comment by byszhoubin** [comment]
I changed branch name from live-sxs to live in pipeline file for integration tests, please help confirm if it makes sense to you.

**Comment by byszhoubin** [comment]
Could you please help review this pull request again. Thanks. @live1206  @AngryBerryMS

**Pull request merged**
