### PR TITLE
make postprocessors work again

### LINKED ISSUE #8578: [Bug] Custom post processors not being loaded
**Describe the bug**
Post processors not being loaded from template/plugins folder.

**To Reproduce**
1. Create a empty template folder, under it place folder for your template, and in that folder - place folder for plugins.
2. In plugins folder, place your post processor
3. Add your post processor in docfx.json

**Expected behavior**
Post processor being loaded.

**Context (please complete the following information):**
- OS: Linux
- Docfx version: 2.64.0

**Additional context**
Tried to use [LastModified](https://github.com/Still34/DocFx.Plugin.LastModified), didn't work (even tried updating dependencies for it on my fork!)
image
This is the warning that i get.

### PR DESCRIPTION
**Pull request by InFTord**
Fixes post processors not being loaded.
Fixes #8578.

### CODE REVIEW

**Review by yufeih — APPROVED** [review]
Thank you @InFTord !

**Comment by yufeih** [comment]
This time the snapshot test failure isn't related to the PR.

**Comment by InFTord** [comment]
Still not sure why now postprocessors stopped working properly.....
Same problem as before - it just can't find them.

**Comment by InFTord** [comment]
> Still not sure why now postprocessors stopped working properly..... Same problem as before - it just can't find them.

My current theory that it can't use template folders for some reason.
изображение

**Pull request merged**
