### PR TITLE
Check internal xref property conflict after map built

### PR DESCRIPTION
**Pull request by mingwli**
Fixing [lazy crashed](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C7%5C5de83821-f44b-0e93-473e-c19393f102fe%5CCommit%5C202009070424567676-javaSDP%5Crawlog.txt?sv=2016-05-31&sr=b&sig=NOgy0OAZMo3C9Rbi4ZJTzaTCbVdM2k8ILinQJQlpg8w%3D&st=2020-09-07T04%3A25%3A37Z&se=2020-10-08T04%3A30%3A37Z&sp=r)

Checking xref property conflict requires evaluate xref property value, and if the value also tries to resolve xref, 💥
image

Validate internal xref properties only once after it's initialized.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/docfx/pull/6515)

### CODE REVIEW

**Review by yufeih — CHANGES_REQUESTED** [review]
`ToXrefMapModel` isn't the right place to put the check.

**Comment by mingwli** [comment]
> `ToXrefMapModel` isn't the right place to put the check.

what's your recommendation?

**Comment by mingwli** [comment]
@yufeih 
a skipped test failed the CI 
https://dev.azure.com/ceapex/Engineering/_build/results?buildId=191537&view=ms.vss-test-web.build-test-results-tab&runId=1276272&paneView=debug&resultId=100843
image

**Comment by mingwli** [comment]
> @yufeih
> a skipped test failed the CI
> https://dev.azure.com/ceapex/Engineering/_build/results?buildId=191537&view=ms.vss-test-web.build-test-results-tab&runId=1276272&paneView=debug&resultId=100843
> image

Indeed the failed test is the 29th(1 based). The test isn't reporting correctly index.
test case:
image
console output:
image
test summary:
image

**Review by yufeih — APPROVED** [review]

**Pull request merged**
