### PR TITLE
fix: try fixing TSA iteration path

### PR DESCRIPTION
**Pull request by herohua**
https://dev.azure.com/ceapex/Engineering/_build/results?buildId=843721&view=logs&j=fa965d9e-e9c2-54a2-3314-91eb96ef2d15&t=e56bb7bb-bb68-5f18-674d-f04270ba1a93

### CODE REVIEW

**Comment by herohua** [comment]
<details><summary>🧭<a href='https://github.com/MicrosoftDocs/azure-docs-pr'>azure-docs-pr</a>(00:01:52.4713372 | exceed 100s, 8241MB)</summary>

```diff
diff --git "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/.publish.json" "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/.publish.json"
index 1da9b8d..ebb8c93 100644
--- "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/.publish.json"
+++ "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/.publish.json"
@@ -619306,7 +619306,6 @@ IMPORTANT: This content is for the older Azure AD v1.0 endpoint, use the Microso
         "alexbuckgit",
         "v-kents",
         "ktoliver",
-        "Oddsor",
         "v-hagamp"
       ],
       "updated_at": "2021-11-12 12:36 AM",
diff --git "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/azure/active-directory/saas-apps/ardoq-tutorial.mta.json" "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/azure/active-directory/saas-apps/ardoq-tutorial.mta.json"
index f6d3a30..4ba4e46 100644
--- "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/azure/active-directory/saas-apps/ardoq-tutorial.mta.json"
+++ "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/azure/active-directory/saas-apps/ardoq-tutorial.mta.json"
@@ -12,7 +12,6 @@
     "alexbuckgit",
     "v-kents",
     "ktoliver",
-    "Oddsor",
     "v-hagamp"
   ],
   "is_dynamic_rendering": true,
diff --git "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/azure/active-directory/saas-apps/ardoq-tutorial.raw.page.json" "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/azure/active-directory/saas-apps/ardoq-tutorial.raw.page.json"
index 7d5e3ad..f2eb51f 100644
--- "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/azure/active-directory/saas-apps/ardoq-tutorial.raw.page.json"
+++ "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/azure/active-directory/saas-apps/ardoq-tutorial.raw.page.json"
@@ -228,12 +228,6 @@
           "display_name": "Kent Sharkey",
           "id": "22481554"
         },
-        {
-          "name": "Oddsor",
-          "profile_url": "https://github.com/Oddsor",
-          "display_name": "Odd A",
-          "id": "3494925"
-        },
         {
           "name": "v-hagamp",
           "profile_url": "https://github.com/v-hagamp",
@@ -252,7 +246,6 @@
       "alexbuckgit",
       "v-kents",
       "ktoliver",
-      "Oddsor",
       "v-hagamp"
     ],
     "updated_at": "2021-11-12 12:36 AM",


``````csharp
 30% | docfx!Microsoft.Docs.Build.ParallelUtility+<>c__DisplayClass2_0`1[System.__Canon].<ForEach>b__0(!0)
 25% | docfx!Microsoft.Docs.Build.DocsetBuilder+<>c__DisplayClass41_1.<Build>b__15(class Microsoft.Docs.Build.FilePath)
 23% | docfx!Microsoft.Docs.Build.PageBuilder.Build(class Microsoft.Docs.Build.ErrorBuilder,class Microsoft.Docs.Build.FilePath)
 21% | Microsoft.Docs.MarkdigExtensions!Microsoft.Docs.MarkdigExtensions.ResolveLinkExtension.UpdateLinks(class Markdig.Syntax.MarkdownObject)
 16% | docfx!Microsoft.Docs.Build.PageBuilder.LoadMarkdown(class Microsoft.Docs.Build.ErrorBuilder,class Microsoft.Docs.Build.FilePath)
 14% | docfx!Microsoft.Docs.Build.MarkdownEngine.ToHtml(class Microsoft.Docs.Build.ErrorBuilder,class System.String,class Microsoft.Docs.Build.SourceInfo,value class Microsoft.Docs.Build.MarkdownPipelineType,class Microsoft.Docs.Build.ConceptualModel,bool)
 13% | Markdig!Markdig.Markdown.ToHtml(class System.String,class Markdig.MarkdownPipeline)
 10% | Markdig!Markdig.Parsers.MarkdownParser.Parse()
  9% | Markdig!Markdig.Renderers.RendererBase.Write(class Markdig.Syntax.MarkdownObject)
  8% | docfx!Microsoft.Docs.Build.MarkdigUtility.<Replace>g__ReplaceCore|7_0(class Markdig.Syntax.MarkdownObject,class System.Func`2<class Markdig.Syntax.MarkdownObject,class Markdig.Syntax.MarkdownObject>)
  6% | docfx!Microsoft.Docs.Build.Docfx+<>c__DisplayClass6_0.<CreateCommand>b__0(class Microsoft.Docs.Build.CommandLineOptions)
  6% | docfx!Microsoft.Docs.Build.Docfx+<>c__DisplayClass4_0.<BuildCommand>b__0(class Microsoft.Docs.Build.CommandLineOptions)
  6% | docfx!Microsoft.Docs.Build.Builder.Run(class Microsoft.Docs.Build.CommandLineOptions,class Microsoft.Docs.Build.Package)
  6% | docfx!Microsoft.Docs.Build.Builder.Build(class Microsoft.Docs.Build.ErrorBuilder,class System.IProgress`1<class System.String>,class System.String[])
  4% | docfx!Microsoft.Docs.Build.MarkdigUtility.Visit(class Markdig.Syntax.MarkdownObject,class System.Func`2<class Markdig.Syntax.MarkdownObject,bool>)
  4% | docfx!Microsoft.Docs.Build.LinkResolver.ResolveLink(value class Microsoft.Docs.Build.SourceInfo`1<class System.String>,class Microsoft.Docs.Build.FilePath,class Microsoft.Docs.Build.FilePath,class Microsoft.Docs.Validation.LinkNode,class System.String)
  4% | docfx!Microsoft.Docs.Build.MarkdownEngine.GetLink(class Microsoft.Docs.Build.LinkInfo)
  4% | docfx!Microsoft.Docs.Build.PageBuilder.CreatePageOutput(class Microsoft.Docs.Build.ErrorBuilder,class Microsoft.Docs.Build.FilePath,class Newtonsoft.Json.Linq.JObject)
  4% | Markdig!Markdig.Renderers.RendererBase.WriteChildren(class Markdig.Syntax.ContainerBlock)
  4% | docfx!Microsoft.Docs.Build.Builder+<>c__DisplayClass8_0.<Build>b__0(class Microsoft.Docs.Build.DocsetBuilder)
  3% | docfx!Microsoft.Docs.Build.DocsetBuilder.Build(class System.String[])
  3% | docfx!Microsoft.Docs.Build.ParallelUtility.ForEach(class Microsoft.Docs.Build.LogScope,class Microsoft.Docs.Build.ErrorBuilder,class System.Collections.Generic.IEnumerable`1<!!0>,class System.Action`1<!!0>)
  3% | docfx!Microsoft.Docs.Build.LinkResolver.TryResolveAbsoluteLink(value class Microsoft.Docs.Build.SourceInfo`1<class System.String>,class Microsoft.Docs.Build.FilePath,class Microsoft.Docs.Build.FilePath,class Microsoft.Docs.Validation.LinkNode,class System.String)
  3% | docfx!Microsoft.Docs.Build.MarkdownEngine.GetImageLink(class System.String,class Markdig.Syntax.MarkdownObject,class System.String,class System.String)
  3% | Markdig!Markdig.Renderers.TextRendererBase.Render(class Markdig.Syntax.MarkdownObject)
  3% | docfx!Microsoft.Docs.Build.Watch`1[System.__Canon].get_Value()
  3% | docfx!Microsoft.Docs.Build.ContentValidator.ValidateLink(class Microsoft.Docs.Build.FilePath,class Microsoft.Docs.Validation.LinkNode)
  3% | docfx!Microsoft.Docs.Build.ErrorBuilder.AddRange(class System.Collections.Generic.IEnumerable`1<class Microsoft.Docs.Build.Error>)
  2% | docfx!Microsoft.Docs.Build.PageBuilder.CreateSystemMetadata(class Microsoft.Docs.Build.ErrorBuilder,class Microsoft.Docs.Build.FilePath,class Microsoft.Docs.Build.UserMetadata)
  2% | docfx!Microsoft.Docs.Build.TocLoader+<>c__DisplayClass22_0.<LoadTocNodes>b__0(int32)

```

</details>

**Comment by herohua** [comment]
<details><summary>🚗🌳💥🤕🚑<a href='https://github.com/MicrosoftDocs/powerbi-docs-pr.de-DE'>powerbi-docs-pr.de-DE</a>(00:00:00, 0MB)</summary>

```
System.InvalidOperationException: '"D:\a\_work\1\RegressionTest\docfx.exe" restore --log "D:/docfx.TestData\regression-test.powerbi-docs-pr.de-DE\.temp\.errors.log" --verbose --stdin' failed in directory 'D:/docfx.TestData\regression-test.powerbi-docs-pr.de-DE\powerbi-docs-pr.de-DE' with exit code 1, message: 
 
   at Microsoft.Docs.Build.RegressionTest.Exec(String fileName, String arguments, String stdin, String cwd, Dictionary`2 env, Boolean ignoreError, Boolean redirectStandardError, Int32[] allowExitCodes, String[] secrets) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 411
   at Microsoft.Docs.Build.RegressionTest.RestoreDependency(String repositoryPath, String docfxConfig, String outputPath) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 239
   at Microsoft.Docs.Build.RegressionTest.Build(RegressionTestResult testResult, String repositoryPath, String outputPath, Options opts, String docfxConfig) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 254
   at Microsoft.Docs.Build.RegressionTest.Test(Options opts, String workingFolder) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 173
   at Microsoft.Docs.Build.RegressionTest.Run(Options opts) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 64

```

</details>

**Comment by herohua** [comment]
<details><summary>🧭<a href='https://github.com/MicrosoftDocs/PowerShell-Docs'>PowerShell-Docs</a>(00:01:18.7933715 | exceed 75s, 4009MB)</summary>



</details>

**Comment by herohua** [comment]
<details><summary>⚠<a href='https://github.com/MicrosoftDocs/VBA-Docs'>VBA-Docs</a>(00:01:00.5107077, 6686 more diff, 2203MB)</summary>

```diff
diff --git "a/D:/docfx.TestData\\regression-test.VBA-Docs\\output/.errors.log" "b/D:/docfx.TestData\\regression-test.VBA-Docs\\.temp/.errors.log"
index 4013960..24e844d 100644
--- "a/D:/docfx.TestData\\regression-test.VBA-Docs\\output/.errors.log"
+++ "b/D:/docfx.TestData\\regression-test.VBA-Docs\\.temp/.errors.log"
@@ -83667,7 +83667,8 @@
   "ms.author": "o365devx",
   "ms.prod": "outlook",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83682,7 +83683,8 @@
   "ms.author": "o365devx",
   "ms.prod": "outlook",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83697,7 +83699,8 @@
   "ms.author": "o365devx",
   "ms.prod": "outlook",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83712,7 +83715,8 @@
   "ms.author": "o365devx",
   "ms.prod": "outlook",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83727,7 +83731,8 @@
   "ms.author": "o365devx",
   "ms.prod": "outlook",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83742,7 +83747,8 @@
   "ms.author": "o365devx",
   "ms.prod": "outlook",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83757,7 +83763,8 @@
   "ms.author": "o365devx",
   "ms.prod": "outlook",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83772,7 +83779,8 @@
   "ms.author": "o365devx",
   "ms.prod": "outlook",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83787,7 +83795,8 @@
   "ms.author": "o365devx",
   "ms.prod": "outlook",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83802,7 +83811,8 @@
   "ms.author": "o365devx",
   "ms.prod": "outlook",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83817,7 +83827,8 @@
   "ms.author": "o365devx",
   "ms.prod": "project-server",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83832,7 +83843,8 @@
   "ms.author": "o365devx",
   "ms.prod": "office",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83847,7 +83859,8 @@
   "ms.author": "o365devx",
   "ms.prod": "office",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83862,7 +83875,8 @@
   "ms.author": "o365devx",
   "ms.prod": "access",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83877,7 +83891,8 @@
   "ms.author": "o365devx",
   "ms.prod": "access",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83892,7 +83907,8 @@
   "ms.author": "o365devx",
   "ms.prod": "access",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83907,7 +83923,8 @@
   "ms.author": "o365devx",
   "ms.prod": "access",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83922,7 +83939,8 @@
   "ms.author": "o365devx",
   "ms.prod": "access",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83937,7 +83955,8 @@
   "ms.author": "o365devx",
   "ms.prod": "visio",
   "ms.technology": "vba",
-  "ms.topic": "reference"
+  "ms.topic": "reference",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83952,7 +83971,8 @@
   "ms.author": "o365devx",
   "ms.prod": "visio",
   "ms.technology": "vba",
-  "ms.topic": "reference"
+  "ms.topic": "reference",


```

</details>

**Comment by herohua** [comment]
<details><summary>⚠<a href='https://github.com/MicrosoftDocs/sql-docs-pr'>sql-docs-pr</a>(00:00:59.0154861, 6069MB)</summary>

```diff
diff --git "a/D:/docfx.TestData\\regression-test.sql-docs-pr\\output/.errors.log" "b/D:/docfx.TestData\\regression-test.sql-docs-pr\\.temp/.errors.log"
index 196ef31..3871766 100644
--- "a/D:/docfx.TestData\\regression-test.sql-docs-pr\\output/.errors.log"
+++ "b/D:/docfx.TestData\\regression-test.sql-docs-pr\\.temp/.errors.log"
@@ -591242,6 +591242,23 @@
   "ms.topic": "conceptual",
   "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main"
 }
+{
+  "message_severity": "warning",
+  "code": "ms-author-invalid",
+  "message": "Invalid value for 'ms.author', 'alexiva' is not a valid Microsoft alias.",
+  "file": "docs/ssma/ssma-diagnostic-data-collection.md",
+  "line": 8,
+  "end_line": 8,
+  "column": 12,
+  "end_column": 19,
+  "log_item_type": "user",
+  "property_path": "ms.author",
+  "ms.author": "alexiva",
+  "ms.prod": "sql",
+  "ms.technology": "ssma",
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main"
+}
 {
   "message_severity": "warning",
   "code": "ms-author-invalid",


```

</details>

**Review by AngryBerryMS — APPROVED** [review]

**Pull request merged**
