### PR TITLE
Enable markdig engine in documentation

### PR DESCRIPTION
**Pull request by qinezh**

### CODE REVIEW

**Comment by vicancy** [comment]
Hi @qinezh Do you think it is ready for docfx to switch to "markdig" as the default engine? 
Related issues: https://github.com/dotnet/docfx/issues/2648 https://github.com/dotnet/docfx/issues/2647

**Comment by qinezh** [comment]
@vicancy I'm afraid not at the moment. There're so many repositories generate documentation without setting the markdown engine explicitly in `docfx.json`. For these repositories, switch to "markdig" as default engine in DocFX would be a breaking change if the documentation aren't written in a CommonMark style.

**Comment by kasper3** [comment]
Instead of coining yet another engine ..
Can `dfm-latest` be updated to base on CommonMark which new GFM is using, instead of old-GFM?
I thought there was no significant difference except for:

`###heading` - used to be allowed, but not anymore

vs.

`### heading` - with one space, works before and after

GitHub guys could also have created a new engine instead of updating GFM, but they decided to take a one-time breaking change. They have many times more documents to support than docfx does.

**Comment by kasper3** [comment]
With the current approach, imo it would take huge amount of time to convince everyone to update to `markdig` engine, e.g. https://github.com/dotnet/docs/blob/e299873564d36e3349ad158d5a98a9c716c75d59/docfx.json#L3

**Comment by qinezh** [comment]
@kasper3 The repo you mentioned will be migrated to use `markdig` before too long. And yes we have to take a one-time breaking change like GitHub, but the timing not right at this moment.

**Comment by vicancy** [comment]
@qinezh Understand that. How about adding that to our DFM documentation, after all, we claimed we are compatible with GFM by default, but actually that is not the case now.

**Pull request merged**
