### PR TITLE
Extract template tests to template.yml to make test clear

### PR DESCRIPTION
**Pull request by v-pegao**
Workitem is [here](https://ceapex.visualstudio.com/Engineering/_workitems/edit/107430/)

|Request|Status|
|---|---|
|extract all template specific tests into a new `template.yml` for the tests to be clearer|in progress|
|based on above, check if we missed any import cases and add them|Not started|

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/docfx/pull/4998)

### CODE REVIEW

**Comment by mingwli** [comment]
@v-pegao please add the following too:
https://github.com/dotnet/docfx/blob/v3/docs/specs/schema.yml#L356
https://github.com/dotnet/docfx/blob/v3/docs/specs/schema.yml#L406
https://github.com/dotnet/docfx/blob/v3/docs/specs/schema.yml#L526

**Comment by v-pegao** [comment]
@mingwli Updated the template.yml

**Comment by yufeih** [comment]
@v-pegao @mingwli @OsmondJiang does this work includes removing TestData.schema.json?

**Comment by mingwli** [comment]
@yufeih @OsmondJiang No I think this issue only address extracting the apply JS/mustache/liquid part into a single yaml file.

**Comment by yufeih** [comment]
@mingwli , ok, can we have another task that git rid of TestData.schema.json?

**Comment by mingwli** [comment]
> @mingwli , ok, can we have another task that git rid of TestData.schema.json?

will track in DevOps here https://ceapex.visualstudio.com/Engineering/_workitems/edit/115502

**Pull request merged**
