### PR TITLE
fix nuget warning

### PR DESCRIPTION
**Pull request by mingwli**
image

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/docfx/pull/7030)

### CODE REVIEW

**Comment by mingwli** [comment]
npm run

**Review by yufeih — APPROVED** [review]
👍

**Comment by yufeih** [comment]
Seems like the fix did not fix the warning

**Comment by mingwli** [comment]
> Seems like the fix did not fix the warning

https://docs.opensource.microsoft.com/tools/nuget_security_analysis.html
image

oneway is make nuget.org upstream of docfx feed, for which I've got no permission :/

**Comment by mingwli** [comment]
image

**Pull request merged**
