### PR TITLE
VS2019 MSBuild adaptions

### PR DESCRIPTION
**Pull request by tibel**
**MSBuild package references**
MSBuild assemblies should be loaded from MSBuild installation directory always. Otherwise there might be issues with loading the wrong assembly. When referencing a package (assembly) that is part of MSBuild it should not be copied to output. The assembly loading is handled by MSBuildLocater.

As the references are not needed by the project, I removed them completely.

**app.config**
I updated the docfx app.config with the content of MSBuild.exe.config from VS2019 installation.

### CODE REVIEW

**Comment by superyyrrzz** [comment]
@tibel Thank you for contribution. The change makes sense to me.

Before this change, I think [VS2019 is required](https://github.com/dotnet/docfx/pull/4595/files#diff-e97ec8467b74412633a717f880a4bdddR107) as I referenced MSBuild 16. After this is merged, users with only VS2017 installed will also work, right?

**Comment by tibel** [comment]
@superyyrrzz I'm not sure if VS2017 will work as in _MsBuildEnvironmentScope.cs_ there is a check for VS2019 only.

**Comment by superyyrrzz** [comment]
I will first on hold this change for the reason same as https://github.com/dotnet/docfx/pull/4709#issuecomment-500445181. I need more test to make sure it works under Linux/Mono.

**Comment by tibel** [comment]
Sure.

As I have noted in https://github.com/dotnet/docfx/pull/4709#issuecomment-500504826 the `15.0` folder is Mono related and has nothing to do with Visual Studio installation.

**Comment by superyyrrzz** [comment]
My test shows it will error under Linux/Mono:
```
[19-06-12 03:54:59.701]Info:[ExtractMetadata]Loading projects...
[19-06-12 03:55:00.424]Warning:[ExtractMetadata](/home/docfx-seed/src/SampleClass1/CatLibrary/CatLibrary.csproj)Error opening project /home/docfx-seed/src/SampleClass1/CatLibrary/CatLibrary.csproj: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
Could not load file or assembly 'Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
Could not load file or assembly 'Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.. Ignored.
[19-06-12 03:55:00.449]Error:Error extracting metadata for /home/docfx-seed/src/SampleClass1/CatLibrary/CatLibrary.csproj: System.NullReferenceException: Object reference not set to an instance of an object
  at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.SaveAllMembersFromCacheAsync () [0x004b7] in <b67cfe4276f149db88efc0eec614a31b>:0
  at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.ExtractMetadataAsync () [0x000f3] in <b67cfe4276f149db88efc0eec614a31b>:0
[19-06-12 03:55:00.455]Info:Completed in 1038.0334 milliseconds


Build failed.
```

From the error message, we can see there DLLs are really needed.

BTW, even without this change, is still cannot work under Linux/Mono:
```
[19-06-12 03:36:27.833]Info:[ExtractMetadata]Loading projects...
[19-06-12 03:36:29.601]Warning:[ExtractMetadata](/home/docfx-seed/src/SampleClass1/CatLibrary/CatLibrary.csproj)Workspace failed with: [Failure] Msbuild failed when processing the file '/home/docfx-seed/src/SampleClass1/CatLibrary/CatLibrary.csproj' with message: The imported project "/usr/lib/mono/msbuild/15.0/bin//Microsoft.CSharp.Core.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  /usr/lib/mono/msbuild/15.0/bin/Microsoft.CSharp.CurrentVersion.targets
[19-06-12 03:36:29.738]Warning:[ExtractMetadata]Project '/home/docfx-seed/src/SampleClass1/CatLibrary/CatLibrary.csproj' does not contain any documents.
[19-06-12 03:36:29.930]Info:[ExtractMetadata]Generating metadata for each project...
[19-06-12 03:36:30.290]Warning:[ExtractMetadata]No metadata is generated for CatLibrary.
[19-06-12 03:36:30.294]Info:Completed in 2661.9686 milliseconds
```

**Comment by tibel** [comment]
The mentioned assemblies are in the mono msbuild folder (C:\Program Files\Mono\lib\mono\msbuild\15.0\bin). So they are not loaded upfront, like MSBuildLocator is doing.

**Comment by tibel** [comment]
@superyyrrzz I think the Mono problem should be handled in a separate issue.

**Comment by superyyrrzz** [comment]
That makes sense to me. This PR can make users with only VS2017 installed keep working. Thank you for contribution!

**Pull request merged**
