### PR TITLE
upgrade docs validation library

### PR DESCRIPTION
**Pull request by RetYn**
[AB#355702](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/355702)
upgrade docs validation library

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/docfx/pull/6963)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/docfx?pullRequest=6963) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docfx?pullRequest=6963) before we can accept your contribution.<br/><br/>:x: RetYn [sign now](https://cla.dotnetfoundation.org/dotnet/docfx?pullRequest=6963)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docfx?pullRequest=6963) it.</sub>

**Review by yufeih — APPROVED** [review]

**Comment by OsmondJiang** [comment]
👍

**Pull request merged**
