### PR TITLE
added default autocollapse functionality

### PR DESCRIPTION
**Pull request by vsi-hvarma**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/docfx/pull/4965)

### CODE REVIEW

**Comment by vsi-hvarma** [comment]
This is intended to fix issue 2878

**Comment by superyyrrzz** [comment]
I find the top navbar is missing after this change for https://github.com/docascode/docfx-seed There is also an E2E test failed for this issue in PR check. Could you take a look?

image

**Comment by vsi-hvarma** [comment]
I'm not sure why docfx-seed is affected, I can take a look at it. The E2E test errors were like this:
Failed   Microsoft.DocAsCode.E2E.Tests.DocfxSeedSiteTest.TestReferencePage
Error Message:
 OpenQA.Selenium.NoSuchElementException : URL: http://localhost:8080/index.html

Can we get some more information about the tests? Are they expecting the navbar not to be collapsed? If so, then the tests are likely incorrect as they are attempting to test for an issue that was reported.

**Comment by superyyrrzz** [comment]
From the error message:
```
---- OpenQA.Selenium.NoSuchElementException : Unable to locate element: {"method":"link text","selector":"API Documentation"}
```
This test try clicking the link `API Documentation` on navbar, but could not find it. It did its job, as it does missing from my screenshot above.

**Comment by superyyrrzz** [comment]
Let me provide more information about the related issue. DocFX mainly has 2 templates:
* *default template*: it ships with docfx tool, and it is what you are using. It expects the root TOC as **top navbar**
* *DOCS template*: it is a private template used for docs.microsoft.com site. It expects the root TOC as **left sidebar**.

The related issue tries to build a *DOCS template* repo with *default template*, so the TOC original used as **left sidebar** is rendered to **top navbar**. Actually, this is not an expected usage to build with the not desired template.

What we can do is to make the result page as readable as it can with some possible compatible code. But basically, it should ensure default template usage is not affected. [docfx-seed](https://github.com/docascode/docfx-seed) is a project you that can use to test default template.

**Comment by superyyrrzz** [comment]
@vsi-hvarma Close as inactivity. Feel free to continue the work when you have time.

**Pull request closed without merging**
