### PR TITLE
add trust cert for DocFX Graph Client app registration

### PR DESCRIPTION
**Pull request by LandoSun**
1. update new DocFX Graph Client Public application id
2. get token through SNI

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/docfx?pullRequest=7511) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docfx?pullRequest=7511) before we can accept your contribution.<br/><br/>:x: LandoSun [sign now](https://cla.dotnetfoundation.org/dotnet/docfx?pullRequest=7511)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docfx?pullRequest=7511) it.</sub>

**Review by yufeih — APPROVED** [review]

**Comment by herohua** [comment]
@mingwli Looks like @LandoSun still would like to switch AAD application to the newly applied one. Can you help review his PR? I don't see a reason why we should hold this back if everything has been setup (e.g. Admin consent).

**Pull request merged**
