### PR TITLE
triger diffs after update regression all ruleset

### PR DESCRIPTION
**Pull request by xichan-ms**
[AB#338038](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/338038)

### CODE REVIEW

**Comment by xichan-ms** [comment]
Diff expected, these diffs are duo to the [PR](https://github.com/dotnet/docfx/pull/6825), as the explanations in that PR, diffs in repos DevSandbox and learn-pr will revert until docs.validation shipped to prod.

**Review by yufeih — APPROVED** [review]

**Pull request merged**
