### PR TITLE
Upgrade to Jint 3.0.0-beta-2046

### PR DESCRIPTION
**Pull request by lahma**
Now targeting main for the Jint upgrade.

### CODE REVIEW

**Comment by yufeih** [comment]
Test passed, but building the docs folder failed with:

> Error running GetOptions function inside template preprocessor: Property 'forEach' of object is not a function

**Comment by lahma** [comment]
This should now be resolved, sharing a static engine instance is not a good thing as engine is now thread-safe. Changed to pass engine in question to type conversion so now at least "works on my machine".

**Review by yufeih — APPROVED** [review]

**Comment by yufeih** [comment]
Awesome thanks!

**Comment by lahma** [comment]
You're welcome,  thanks for accepting the PR!

**Pull request merged**
