### PR TITLE
update docfx workflow

### PR DESCRIPTION
**Pull request by vicancy**
@chenkennt @superyyrrzz @vwxyzh

### CODE REVIEW

**Comment by chenkennt** [comment]
docfx metadata
3. Link should be updated when comments are extracted

This is not true now

**Comment by chenkennt** [comment]
typo: output documentation

**Comment by chenkennt** [comment]
add plugin part in the diagram?

**Comment by herohua** [comment]
minor: Can you add a '3' before optional: `docfx serve`? Current big 'O' looks weird...

**Comment by vicancy** [comment]
@herohua 'O' is by design, as `docfx serve` is not necessarily step 3

**Comment by herohua** [comment]
@vicancy I see, no big issue. :)

**Comment by vicancy** [comment]
@chenkennt Updated

**Comment by chenkennt** [comment]
still typo..
docum**a**ntation

**Comment by chenkennt** [comment]
Docfx -> DocFX

**Comment by chenkennt** [comment]
Change "DFM to HTML" to a round rectangle

**Comment by vicancy** [comment]
@chenkennt updated

**Comment by chenkennt** [comment]
:+1:

**Pull request closed without merging**
