### PR TITLE
Row markdig extension

### PR DESCRIPTION
**Pull request by wibjorn**
Correct mistake for writing attributes, add test to test production/write attributes code for row.cs

### CODE REVIEW

**Comment by wibjorn** [comment]
Ready for merge. As I said in the previous PR, someone with write access will need to perform the merge.

**Comment by adkinn** [comment]
Thanks for the fix and review @yishengjin1413 and @vicancy 

Can we get this fix shipped as another hotfix? Apologies for the trouble, now we know how to write extensions :)

/cc @wibjorn

**Comment by adkinn** [comment]
Any updates on this hotfix going live? @vicancy @yishengjin1413

**Comment by vicancy** [comment]
@adkinn This change is already in master and released in docfx 2.32.2

**Comment by vicancy** [comment]
@adkinn Confirmed with @fenxu that we still need OPS support to make this hotfix go live.... Is it OK to release this change next Monday along with 2.33 release?

**Comment by adkinn** [comment]
Yes, since the regular release is so close that makes sense. Thanks for the update @vicancy

**Pull request merged**
