### PR TITLE
Added multiple merge operation support

### PR DESCRIPTION
**Pull request by lextm**
As stated in #2286 I think multiple merge operations should be allowed.

However, this would be a breaking change to the JSON schema.

### CODE REVIEW

**Comment by vicancy** [comment]
This is a breaking change, we can use a custom JsonConverter to support both, as similar to https://github.com/dotnet/docfx/blob/dev/src/docfx/Models/FileMappingConverter.cs

**Comment by lextm** [comment]
@vicancy I just added the converter as you described. It seems to work. Any idea how I should add `MergeCommandTest` in `docfx.Tests` project?

**Comment by lextm** [comment]
Sounds like GitHub does not sync that commit, https://github.com/lextm/docfx/commit/9cf7d13b9c282fad9b16a2e69f14d1cf60524ceb

**Comment by vicancy** [comment]
Hi @lextm , how about a serialization case in https://github.com/dotnet/docfx/blob/dev/test/docfx.Tests/JsonConverterTest.cs and a Merge case in https://github.com/dotnet/docfx/blob/dev/test/docfx.Tests/CompositeCommandTest.cs ?

**Comment by vicancy** [comment]
Hi @lextm I merged this change, and you can open another PR for test cases. Thanks for your contributions to it.

**Pull request merged**
