### PR TITLE
get msgraph token through SNI

### PR DESCRIPTION
**Pull request by LandoSun**
1. Get msgraph token through SNI
2. Update ms graph cert application id

### CODE REVIEW

**Comment by LandoSun** [comment]
remove test pr

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/docfx?pullRequest=7493) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docfx?pullRequest=7493) before we can accept your contribution.<br/><br/>:x: LandoSun [sign now](https://cla.dotnetfoundation.org/dotnet/docfx?pullRequest=7493)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docfx?pullRequest=7493) it.</sub>

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/docfx?pullRequest=7493) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docfx?pullRequest=7493) before we can accept your contribution.<br/><br/>:x: LandoSun [sign now](https://cla.dotnetfoundation.org/dotnet/docfx?pullRequest=7493)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docfx?pullRequest=7493) it.</sub>

**Pull request closed without merging**
