### PR TITLE
use auto property style when no attribute for get/set

### PR DESCRIPTION
**Pull request by vwxyzh**
@chenkennt @superyyrrzz @hellosnow @ansyral @qinezh 
#251

### CODE REVIEW

**Comment by qinezh** [comment]
`private set` ?

**Comment by hellosnow** [comment]
:shipit:

**Comment by superyyrrzz** [comment]
:shipit:

**Comment by qinezh** [comment]
:shipit:

**Comment by vwxyzh** [comment]
`private` or `internal` won't appear in document.

**Comment by vwxyzh** [comment]
ci seems not working now ...

**Pull request merged**
