### PR TITLE
update incremental for post processor

### PR DESCRIPTION
**Pull request by vwxyzh**
@chenkennt @hellosnow @ansyral @superyyrrzz @qinezh @vicancy

### CODE REVIEW

**Comment by superyyrrzz** [comment]
:shipit:

**Comment by hellosnow** [comment]
:shipit:

**Comment by qinezh** [comment]
:shipit:

**Comment by ansyral** [comment]
:shipit:

**Comment by hellosnow** [comment]
>         private static IEnumerable<string> GetOutputRelativePaths(List<ManifestItem> items, string excludeType = null)

can be removed?

---
Refers to: src/Microsoft.DocAsCode.Build.Engine/PostProcessors/PostProcessorsHandlerWithIncremental.cs:203 in fa0048e. [](commit_id = fa0048e7165ff0f4443ed1f6f8aeeda634fe6613, deletion_comment = False)

**Pull request merged**
