### PR TITLE
Fix bug that search-stopwords.json not found

### PR DESCRIPTION
**Pull request by qinezh**
@superyyrrzz @vwxyzh @hellosnow @ansyral @chenkennt

### CODE REVIEW

**Comment by superyyrrzz** [comment]
also update `iframe.html.zip` and `statictoc.zip`

**Comment by qinezh** [comment]
@superyyrrzz updated

**Comment by superyyrrzz** [comment]
:+1:

**Comment by hellosnow** [comment]
:shipit:

**Pull request merged**
