### PR TITLE
Renamed TocDocFxCreation to DocFxTocGenerator. Added DocFx Quick Start.

### PR DESCRIPTION
**Pull request by mtirionMSFT**
Changed the tools section in the Documentation\Templates & Plugins. As one of the maintainers of the DocFx Companion Tools we have made some changes, which should be reflected in the Tools section.
- TocDocFxCreation tool was renamed to DocFxTocGenerator
- DocFx Quick Start (based on the DocFx Companion Tools) was added as tool
- The Quick Start replaces the links to the pipeline samples for validation and build tools
- Removed the unused images for the removed tools
- Added images for DocFxTocGenerator and DocFxQuickStart.

As this is a documentation change only, no tests are included.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/docfx?pullRequest=7866) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docfx?pullRequest=7866) before we can accept your contribution.<br/><br/>:x: mtirionMSFT [sign now](https://cla.dotnetfoundation.org/dotnet/docfx?pullRequest=7866)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docfx?pullRequest=7866) it.</sub>

**Comment by Ellerbach** [comment]
Thanks @mtirion for the improvements. And pointing on the startkit rather than the older page.

**Review by Ellerbach — APPROVED** [review]
Thanks for the changes!

**Review by yufeih — APPROVED** [review]

**Comment by yufeih** [comment]
Thank you @mtirionMSFT !

**Pull request merged**
