### PR TITLE
HOTFIX - 166016 legacy code snippet build suggestion

### PR DESCRIPTION
**Pull request by adunndevster**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/docfx/pull/5505)

### CODE REVIEW

**Comment by superyyrrzz** [comment]
Some tests need to be fixed.

**Comment by adunndevster** [comment]
My bad. Probably related to expecting this error. On it!

**Comment by superyyrrzz** [comment]
@adunndevster Thank you! I am merging this.

Per discussion in email, we will not deploy a hotfix for this. Instead, we will use an OPS config to filter out the suggestion for now.

**Comment by adunndevster** [comment]
Thanks @superyyrrzz !

**Pull request merged**
