### PR TITLE
fetch without depth option

### PR DESCRIPTION
**Pull request by OsmondJiang**
when fetch with depth option, the `branch` build and `pr` build use different options(1 for branch, 9999999 for pr). This will cause switching which cause performance issue.

With this change, the branch build without CRR cache will slow.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/docfx/pull/4997)

### CODE REVIEW

**Comment by OsmondJiang** [comment]
image

**Comment by yufeih** [comment]
Can you test locally if this is a breaking change? I 'm not sure if you need to pass `--unshallow` to turn a repo cloned using `--depth 1` into a repo with full branch info.

If this is a breaking change, you'll need to change the directory name.

**Comment by OsmondJiang** [comment]
> Can you test locally if this is a breaking change? I 'm not sure if you need to pass `--unshallow` to turn a repo cloned using `--depth 1` into a repo with full branch info. (That is why I use --depth 999999 instead of not specifying a --depth)
> 
> If this is a breaking change, you'll need to change the directory name.

Good point, I am going to test it locally. But actually it's a fetch operation, so I don't think there is a big problem.

**Comment by OsmondJiang** [comment]
image


The failed test has nothing to do with this PR, @928PJY  would you please help to take a look?

**Comment by yufeih** [comment]
@herohua seems PAT for https://github.com/VSC-Service-Account has expired, we need a new one

**Comment by 928PJY** [comment]
you have re-trigger the CI, I cannot see the build log anymore, but from the screenshot, the error message is a little bit confused, @yufeih@live.com any idea about it?

---
In reply to: [521908700](https://github.com/dotnet/docfx/pull/4997#issuecomment-521908700) [](ancestors = 521908700)

**Comment by OsmondJiang** [comment]
> you have re-trigger the CI, I cannot see the build log anymore, but from the screenshot, the error message is a little bit confused, @[yufeih@live.com](mailto:yufeih@live.com) any idea about it?
> 
> In reply to: [521908700](https://github.com/dotnet/docfx/pull/4997#issuecomment-521908700) [](ancestors = 521908700)

It's caused by Razor file watching issue, let's create a bug for tracking: https://ceapex.visualstudio.com/Engineering/_workitems/edit/113897

**Pull request merged**
