### PR TITLE
feat: toggle log severity using rules config

### LINKED ISSUE #9459: [Bug] System.Data warnings for .NET 8 WPF assemblies
**Describe the bug**
Running `docfx metadata` on a .NET 8 WPF DLL generates a bunch of wrong warnings.
Since we use `--warningsAsErrors`, this is a blocker for us. :(

The transitive dependency `DirectWriteForwarder.dll` references assemblies from .NET 8 and .NET Framework. `UniversalAssemblyResolver` cannot handle this.

**To Reproduce**
1. Create a simple WPF assembly with
```
<TargetFramework>net8.0-windows</TargetFramework>
<UseWPF>true</UseWPF>
```
2. Configure `docfx.json` to process assemblies (the problem does **not** occur when processing project files)

```json
{
  "metadata": [
    {
      "src": [
        {
          "files": ["artifacts/assemblies/*.dll"],
          "src": "./"
        }
      ],
      "dest": "api"
    }
  ]
}
``` 
3. Execute ```dotnet docfx metadata .\docfx.json```

This results in the following warnings:
```
dotnet docfx metadata .\docfx.json
                                                                           Using .NET Core SDK 8.0.100
Loading assembly C:/Users/hahn/Projects/DocFxTest/artifacts/assemblies/DocFxWarningTest.dll
warning: Unable to resolve assembly reference System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
warning: Unable to resolve assembly reference System.Data.Odbc, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
warning: Unable to resolve assembly reference System.Data.OleDb, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
warning: Unable to resolve assembly reference System.IO.Ports, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
warning: Unable to resolve assembly reference System.Runtime.Serialization.Schema, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
warning: Unable to resolve assembly reference System.ServiceModel.Syndication, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
warning: Unable to resolve assembly reference System.ServiceProcess.ServiceController, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Processing DocFxWarningTest
Creating output...


Build succeeded with warning.

    7 warning(s)
    0 error(s)
```

**Expected behavior**
There should be no warnings.

**Context (please complete the following information):**
- OS: Windows 11
- Docfx version: 2.74.0+0a19218b660d592013a1d75479f013d69a6c5d71

**Additional context**
I ran docfx in the debugger and was able to see where the dependency is coming from:

`PresentationCore -> DirectWriteForwarder -> System.Data -> System.Data.SqlClient`

`DirectWriteForwarder` is referencing `System.Data` from **.NET Framework** (`C:\Windows\Microsoft.NET\Framework64\v4.0.30319\System.Data.dll`). 

image

`UniversalAssemblyResolver.FindAssemblyFile` in `CompilationHelper` is resolving `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Data.dll` instead, which is a reference assembly that only contains forwarded types.

image

Since these references with 0.0.0.0 version cannot be resolved, the warnings are generated.

### PR DESCRIPTION
**Pull request by yufeih**
Enables toggle log severity based on log code in `docfx.json` using `rules` such as:

```json
{
  "rules": {
    "InvalidAssemblyReference": "info"
  }
}
```

Adds the following error code for `metadata` command:
- `InvalidAssemblyReference`
- `InvalidCref`
- `InvalidXmlComment`
- `CodeNotFound`

This does not fix #9459 but provides a way to suppress warnings no per error code.

### CODE REVIEW

**Comment by bitbonk** [comment]
@yufeih Did you ever consider a way to identify and then ignore docfx warnings individually?
Like I can with the CS0000 compiler warnings or  with the Diagnostics ID in some [Attributes](https://learn.microsoft.com/en-us/dotnet/api/system.obsoleteattribute.diagnosticid?view=net-7.0) and Roslyn analyzers?

**Comment by yufeih** [comment]
Let's see if I understand your question: this change would allow individual warnings to be ignored at the error code level, similar to CS0000/Diagnostics ID (although not all warnings/errors have a code today). Are you looking for suppressing levels at an even more granular level such as `#pragma warning disable`?

**Comment by bitbonk** [comment]
I think as a first step it would be cool if all warnings/errors that docfx can produce would have an ID and the severity of that warning can be configure globally for a build (e.g. in docfx.json).

Being able to do control the warnings occurrences _individually_ similar to `#pragma warning disable` might be nice to have, but I suppose that poses the question where one would write down that  `#pragma warning disable`, not all warnings can be associated with a location in a markdown file.

**Comment by yufeih** [comment]
That make sense and is exactly what this PR is aiming for.

**Pull request merged**
