### PR TITLE
warning when use tabbed conceptual for learn repo

### PR DESCRIPTION
**Pull request by xichan-ms**
[AB#338038](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/338038)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/docfx/pull/6825)

### CODE REVIEW

**Review by yufeih — APPROVED** [review]

**Comment by yufeih** [comment]
@xichan-ms , seems like your fix isn't complete

**Comment by xichan-ms** [comment]
**Through careful investigating, the diffs are by design, the following are some explanations,**

**for azure-devops-docs-pr:**
the deleting warning is due to the bug fixing of apex validation.

**for DevSandbox, learn-pr**
the new warnings related to headings and codeblocks is duo to the filter removing in DocsValidationExtensions.cs, and this repo use prod ruleset, so the new warnings will be removed until docs.validation ship to prod and exclude content type learningpath, module, moduleunit in prod portal.

**for docs, VBA-Docs:** 
the new warnings related to table column-header-missing is duo to the fixing of apex validation, and these warnings was made before, refers to original [error.log](https://dev.azure.com/ceapex/Engineering/_git/docfx.TestData/commit/b4f27c240941326f681ec1197478f0ffc7556ef6?refName=refs%2Fheads%2Fdocs&path=%2Foutput%2F.errors.log&_a=compare).

**Pull request merged**
