### PR TITLE
Using nuget to install dataflow.dll

### PR DESCRIPTION
**Pull request by qinezh**

### CODE REVIEW

**Comment by superyyrrzz** [comment]
:shipit:

**Comment by vwxyzh** [comment]
:+1:

**Comment by hellosnow** [comment]
:shipit:

**Comment by superyyrrzz** [comment]
tried this, but not work...

Warning: Error opening solution C:/docfx-seed/src/SampleClass1/SampleClass1.sln: Could not load file or assembly 'System.Threading.Tasks.Dataflow, Version=4.5.24.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.. Ignored.

**Pull request closed without merging**
