### PR TITLE
fix: TSA config should include project and org name

### PR DESCRIPTION
**Pull request by herohua**

### CODE REVIEW

**Comment by herohua** [comment]
<details><summary>🚗🌳💥🤕🚑<a href='https://github.com/MicrosoftDocs/powerbi-docs-pr.de-DE'>powerbi-docs-pr.de-DE</a>(00:00:00, 0MB)</summary>

```
System.InvalidOperationException: '"D:\a\_work\1\RegressionTest\docfx.exe" restore --log "D:/docfx.TestData\regression-test.powerbi-docs-pr.de-DE\.temp\.errors.log" --verbose --stdin' failed in directory 'D:/docfx.TestData\regression-test.powerbi-docs-pr.de-DE\powerbi-docs-pr.de-DE' with exit code 1, message: 
 
   at Microsoft.Docs.Build.RegressionTest.Exec(String fileName, String arguments, String stdin, String cwd, Dictionary`2 env, Boolean ignoreError, Boolean redirectStandardError, Int32[] allowExitCodes, String[] secrets) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 411
   at Microsoft.Docs.Build.RegressionTest.RestoreDependency(String repositoryPath, String docfxConfig, String outputPath) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 239
   at Microsoft.Docs.Build.RegressionTest.Build(RegressionTestResult testResult, String repositoryPath, String outputPath, Options opts, String docfxConfig) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 254
   at Microsoft.Docs.Build.RegressionTest.Test(Options opts, String workingFolder) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 173
   at Microsoft.Docs.Build.RegressionTest.Run(Options opts) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 64

```

</details>

**Comment by herohua** [comment]
<details><summary>🧭<a href='https://github.com/MicrosoftDocs/learn-pr'>learn-pr</a>(00:01:42.0898190 | exceed 100s, 6581MB)</summary>



</details>

**Comment by herohua** [comment]
<details><summary>🧭<a href='https://github.com/MicrosoftDocs/PowerShell-Docs'>PowerShell-Docs</a>(00:01:21.4526566 | exceed 75s, 3994MB)</summary>



</details>

**Comment by herohua** [comment]
<details><summary>⚠<a href='https://github.com/MicrosoftDocs/VBA-Docs'>VBA-Docs</a>(00:01:02.1382862, 6686 more diff, 2234MB)</summary>

```diff
diff --git "a/D:/docfx.TestData\\regression-test.VBA-Docs\\output/.errors.log" "b/D:/docfx.TestData\\regression-test.VBA-Docs\\.temp/.errors.log"
index 4013960..24e844d 100644
--- "a/D:/docfx.TestData\\regression-test.VBA-Docs\\output/.errors.log"
+++ "b/D:/docfx.TestData\\regression-test.VBA-Docs\\.temp/.errors.log"
@@ -83667,7 +83667,8 @@
   "ms.author": "o365devx",
   "ms.prod": "outlook",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83682,7 +83683,8 @@
   "ms.author": "o365devx",
   "ms.prod": "outlook",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83697,7 +83699,8 @@
   "ms.author": "o365devx",
   "ms.prod": "outlook",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83712,7 +83715,8 @@
   "ms.author": "o365devx",
   "ms.prod": "outlook",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83727,7 +83731,8 @@
   "ms.author": "o365devx",
   "ms.prod": "outlook",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83742,7 +83747,8 @@
   "ms.author": "o365devx",
   "ms.prod": "outlook",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83757,7 +83763,8 @@
   "ms.author": "o365devx",
   "ms.prod": "outlook",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83772,7 +83779,8 @@
   "ms.author": "o365devx",
   "ms.prod": "outlook",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83787,7 +83795,8 @@
   "ms.author": "o365devx",
   "ms.prod": "outlook",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83802,7 +83811,8 @@
   "ms.author": "o365devx",
   "ms.prod": "outlook",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83817,7 +83827,8 @@
   "ms.author": "o365devx",
   "ms.prod": "project-server",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83832,7 +83843,8 @@
   "ms.author": "o365devx",
   "ms.prod": "office",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83847,7 +83859,8 @@
   "ms.author": "o365devx",
   "ms.prod": "office",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83862,7 +83875,8 @@
   "ms.author": "o365devx",
   "ms.prod": "access",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83877,7 +83891,8 @@
   "ms.author": "o365devx",
   "ms.prod": "access",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83892,7 +83907,8 @@
   "ms.author": "o365devx",
   "ms.prod": "access",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83907,7 +83923,8 @@
   "ms.author": "o365devx",
   "ms.prod": "access",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83922,7 +83939,8 @@
   "ms.author": "o365devx",
   "ms.prod": "access",
   "ms.technology": "vba",
-  "ms.topic": "conceptual"
+  "ms.topic": "conceptual",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83937,7 +83955,8 @@
   "ms.author": "o365devx",
   "ms.prod": "visio",
   "ms.technology": "vba",
-  "ms.topic": "reference"
+  "ms.topic": "reference",
+  "document_url": "https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/image-inline?branch=main"
 }
 {
   "message_severity": "suggestion",
@@ -83952,7 +83971,8 @@
   "ms.author": "o365devx",
   "ms.prod": "visio",
   "ms.technology": "vba",
-  "ms.topic": "reference"
+  "ms.topic": "reference",


```

</details>

**Comment by herohua** [comment]
<details><summary>🧭<a href='https://github.com/MicrosoftDocs/azure-docs-pr'>azure-docs-pr</a>(00:01:55.7909916 | exceed 100s, 9628MB)</summary>

```csharp
 28% | docfx!Microsoft.Docs.Build.ParallelUtility+<>c__DisplayClass2_0`1[System.__Canon].<ForEach>b__0(!0)
 24% | docfx!Microsoft.Docs.Build.DocsetBuilder+<>c__DisplayClass41_1.<Build>b__15(class Microsoft.Docs.Build.FilePath)
 22% | docfx!Microsoft.Docs.Build.PageBuilder.Build(class Microsoft.Docs.Build.ErrorBuilder,class Microsoft.Docs.Build.FilePath)
 19% | Microsoft.Docs.MarkdigExtensions!Microsoft.Docs.MarkdigExtensions.ResolveLinkExtension.UpdateLinks(class Markdig.Syntax.MarkdownObject)
 15% | docfx!Microsoft.Docs.Build.PageBuilder.LoadMarkdown(class Microsoft.Docs.Build.ErrorBuilder,class Microsoft.Docs.Build.FilePath)
 13% | docfx!Microsoft.Docs.Build.MarkdownEngine.ToHtml(class Microsoft.Docs.Build.ErrorBuilder,class System.String,class Microsoft.Docs.Build.SourceInfo,value class Microsoft.Docs.Build.MarkdownPipelineType,class Microsoft.Docs.Build.ConceptualModel,bool)
 12% | Markdig!Markdig.Markdown.ToHtml(class System.String,class Markdig.MarkdownPipeline)
  9% | Markdig!Markdig.Parsers.MarkdownParser.Parse()
  7% | Markdig!Markdig.Renderers.RendererBase.Write(class Markdig.Syntax.MarkdownObject)
  6% | docfx!Microsoft.Docs.Build.Docfx+<>c__DisplayClass6_0.<CreateCommand>b__0(class Microsoft.Docs.Build.CommandLineOptions)
  6% | docfx!Microsoft.Docs.Build.MarkdigUtility.<Replace>g__ReplaceCore|7_0(class Markdig.Syntax.MarkdownObject,class System.Func`2<class Markdig.Syntax.MarkdownObject,class Markdig.Syntax.MarkdownObject>)
  6% | docfx!Microsoft.Docs.Build.Docfx+<>c__DisplayClass4_0.<BuildCommand>b__0(class Microsoft.Docs.Build.CommandLineOptions)
  6% | docfx!Microsoft.Docs.Build.Builder.Run(class Microsoft.Docs.Build.CommandLineOptions,class Microsoft.Docs.Build.Package)
  6% | docfx!Microsoft.Docs.Build.Builder.Build(class Microsoft.Docs.Build.ErrorBuilder,class System.IProgress`1<class System.String>,class System.String[])
  4% | docfx!Microsoft.Docs.Build.MarkdigUtility.Visit(class Markdig.Syntax.MarkdownObject,class System.Func`2<class Markdig.Syntax.MarkdownObject,bool>)
  4% | docfx!Microsoft.Docs.Build.PageBuilder.CreatePageOutput(class Microsoft.Docs.Build.ErrorBuilder,class Microsoft.Docs.Build.FilePath,class Newtonsoft.Json.Linq.JObject)
  4% | docfx!Microsoft.Docs.Build.Builder+<>c__DisplayClass8_0.<Build>b__0(class Microsoft.Docs.Build.DocsetBuilder)
  3% | docfx!Microsoft.Docs.Build.MarkdownEngine.GetLink(class Microsoft.Docs.Build.LinkInfo)
  3% | docfx!Microsoft.Docs.Build.DocsetBuilder.Build(class System.String[])
  3% | docfx!Microsoft.Docs.Build.LinkResolver.ResolveLink(value class Microsoft.Docs.Build.SourceInfo`1<class System.String>,class Microsoft.Docs.Build.FilePath,class Microsoft.Docs.Build.FilePath,class Microsoft.Docs.Validation.LinkNode,class System.String)
  3% | docfx!Microsoft.Docs.Build.ParallelUtility.ForEach(class Microsoft.Docs.Build.LogScope,class Microsoft.Docs.Build.ErrorBuilder,class System.Collections.Generic.IEnumerable`1<!!0>,class System.Action`1<!!0>)
  3% | Markdig!Markdig.Renderers.RendererBase.WriteChildren(class Markdig.Syntax.ContainerBlock)
  3% | docfx!Microsoft.Docs.Build.Watch`1[System.__Canon].get_Value()
  3% | docfx!Microsoft.Docs.Build.LinkResolver.TryResolveAbsoluteLink(value class Microsoft.Docs.Build.SourceInfo`1<class System.String>,class Microsoft.Docs.Build.FilePath,class Microsoft.Docs.Build.FilePath,class Microsoft.Docs.Validation.LinkNode,class System.String)
  2% | docfx!Microsoft.Docs.Build.MarkdownEngine.GetImageLink(class System.String,class Markdig.Syntax.MarkdownObject,class System.String,class System.String)
  2% | docfx!Microsoft.Docs.Build.ErrorBuilder.AddRange(class System.Collections.Generic.IEnumerable`1<class Microsoft.Docs.Build.Error>)
  2% | docfx!Microsoft.Docs.Build.PageBuilder.CreateSystemMetadata(class Microsoft.Docs.Build.ErrorBuilder,class Microsoft.Docs.Build.FilePath,class Microsoft.Docs.Build.UserMetadata)
  2% | docfx!Microsoft.Docs.Build.DocsValidationExtension+<>c__DisplayClass0_0.<UseDocsValidation>b__0(class Markdig.Syntax.MarkdownDocument)
  2% | docfx!Microsoft.Docs.Build.ContentValidator.ValidateLink(class Microsoft.Docs.Build.FilePath,class Microsoft.Docs.Validation.LinkNode)
  2% | Markdig!Markdig.Renderers.TextRendererBase.Render(class Markdig.Syntax.MarkdownObject)

```

</details>

**Review by yufeih — APPROVED** [review]

**Pull request merged**
