### PR TITLE
upgrade NuGet.Protocol

### PR DESCRIPTION
**Pull request by YunshuMeg**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/docfx?pullRequest=8235) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docfx?pullRequest=8235) before we can accept your contribution.<br/><br/>:x: YunshuMeg [sign now](https://cla.dotnetfoundation.org/dotnet/docfx?pullRequest=8235)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docfx?pullRequest=8235) it.</sub>

**Comment by yufeih** [comment]
@YunshuMeg Please check into `dev` branch and sign CLA

**Comment by YunshuMeg** [comment]
> @YunshuMeg Please check into `dev` branch and sign CLA

the Nuget.Protocol in dev branch is 6.3.0 version, so I didn't upgrade in dev branch

**Comment by yufeih** [comment]
> > @YunshuMeg Please check into `dev` branch and sign CLA
> 
> the Nuget.Protocol in dev branch is 6.3.0 version, so I didn't upgrade in dev branch

Then we need to release dev to master.

**Comment by YunshuMeg** [comment]
> > > @YunshuMeg Please check into `dev` branch and sign CLA
> > 
> > 
> > the Nuget.Protocol in dev branch is 6.3.0 version, so I didn't upgrade in dev branch
> 
> Then we need to release dev to master.

I received another CG alert for dev branch that we need to upgrade same package from 6.3 to 6.3.1. 
I create another PR to dev then.

**Pull request closed without merging**
