### PR TITLE
Refine merger definition in ApplyOverwriteDocument

### PR DESCRIPTION
**Pull request by hellosnow**
@vwxyzh @qinezh @chenkennt @superyyrrzz @ansyral @vicancy

### CODE REVIEW

**Comment by superyyrrzz** [comment]
:shipit:

**Comment by qinezh** [comment]
:shipit:

**Comment by qinezh** [comment]
one question: why choose `override method` instead of `override field` directly in this case?

**Comment by hellosnow** [comment]
Fields cannot be overridden...

---
In reply to: [266609831](https://github.com/dotnet/docfx/pull/996#issuecomment-266609831) [](ancestors = 266609831)

**Comment by qinezh** [comment]
Sorry, what I mean is Property `protected override MergerFacade Merger { get; }`

**Comment by hellosnow** [comment]
Since want to reuse IMerger as MergerDecorator, to fill in MergerFacade, so the variable is IMerger instead of MergerFacade. For the GetMerger() method, I think it's both ok for override method or override property.

---
In reply to: [266618725](https://github.com/dotnet/docfx/pull/996#issuecomment-266618725) [](ancestors = 266618725)

**Pull request merged**
