### PR TITLE
add yaml deserializer with fallback.

### PR DESCRIPTION
**Pull request by vwxyzh**

### CODE REVIEW

**Comment by superyyrrzz** [comment]
:shipit:

**Comment by vicancy** [comment]
Can I provide multiple fallbacks?

**Comment by vwxyzh** [comment]
yes.

---
In reply to: [321495245](https://github.com/dotnet/docfx/pull/1942#issuecomment-321495245) [](ancestors = 321495245)

**Comment by hellosnow** [comment]
:shipit:

**Pull request merged**
