### PR TITLE
fixes #156 by blacklisting node_modules and bower_components

### LINKED ISSUE #156: PathTooLongException
Hi, I'm wondering if anyone else has experienced a `PathTooLongException` when generating docs, and if there is a workaround.

### PR DESCRIPTION
**Pull request by Eonasdan**
fixes #156 by blacklisting node_modules and bower_components folders from FileGlob scan

### CODE REVIEW

**Comment by Eonasdan** [comment]
I have a client project waiting for this fix before the other developers can use it. Any update on this?

**Comment by vicancy** [comment]
Hi @Eonasdan , I am afraid this logic is too hard coded to be part of the glob logic.

For the `PathTooLongException` for nested `node_modules`, we also encountered similar issue when using `gulp`, and we work around the issue by adding the deep nested dependencies to `devDependencies` section to `package.json`, as shown in https://github.com/dotnet/docfx/blob/dev/src/docfx.website.themes/default/package.json#L18, hope the info helps.

**Comment by Eonasdan** [comment]
@vicancy I understand the hard coded part.

Could it be read from a config file instead?

    <add key="FileGlobBlackList" value="node_modules,bower_components"/>

**Comment by vicancy** [comment]
How about a `.globignore` as similar to `.gitignore`? @chenkennt @vwxyzh what's your opinion?

**Comment by Eonasdan** [comment]
@vicancy @chenkennt @vwxyzh what would like to do with this? As I mentioned, this is currently a blocking issue for one of my client projects.

Also, I haven't done a lot with the new dnx projects. How do I debug the project without running `build.cmd`, try, fail, `build.cmd` again? F5 in VS2015 seems to attempt to restore the nuget packages but always fails. I can create a separate issue for this if needed.

**Comment by chenkennt** [comment]
why can't we use `exclude` to filter `node_modules` folder? @superyyrrzz to take a look.

**Comment by superyyrrzz** [comment]
@chenkennt `exclude` doesn't work for now because exception has be thrown before checking excluded files. I create a PR to fix this.

**Comment by superyyrrzz** [comment]
@Eonasdan It's fixed in dev branch in https://github.com/dotnet/docfx/commit/22dcba0373b3435e91ad9b02bf48f354d736687c. You can use `"exclude": ["node_modules/", "bower_components/"]` to avoid the exception.

**Comment by Eonasdan** [comment]
your commit doesn't work for me. Tried it in a test project.

```
Info: Completed executing in 419.9409 milliseconds.
Error: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 37
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 51
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 51
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 51
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 51
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 51
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 51
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 51
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 51
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 51
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 51
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 51
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 51
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 51
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 51
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesCore>d__1.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 29
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.DocAsCode.GlobUtility.ExpandFileMapping(String baseDirectory, FileMapping fileMapping) in C:\projects\GitHub\docfx\src\docfx\Glob\GlobUtility.cs:line 31
   at Microsoft.DocAsCode.SubCommands.MetadataCommand.ConvertToInputModel(MetadataJsonItemConfig configModel) in C:\projects\GitHub\docfx\src\docfx\SubCommands\MetadataCommand.cs:line 93
   at Microsoft.DocAsCode.SubCommands.MetadataCommand.<GetInputModels>d__11.MoveNext() in C:\projects\GitHub\docfx\src\docfx\SubCommands\MetadataCommand.cs:line 84
   at Microsoft.DocAsCode.SubCommands.MetadataCommand.Exec(SubCommandRunningContext context) in C:\projects\GitHub\docfx\src\docfx\SubCommands\MetadataCommand.cs:line 34
   at Microsoft.DocAsCode.SubCommands.CompositeCommand.Exec(SubCommandRunningContext context) in C:\projects\GitHub\docfx\src\docfx\SubCommands\CompositeCommand.cs:line 38
   at Microsoft.DocAsCode.Program.ExecSubCommand(String[] args) in C:\projects\GitHub\docfx\src\docfx\Program.cs:line 75


Build failed.
Error: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 37
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 51
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 51
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 51
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 51
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 51
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 51
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 51
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 51
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 51
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 51
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 51
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 51
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 51
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 51
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesCore>d__1.MoveNext() in C:\projects\GitHub\docfx\src\Microsoft.DocAsCode.Glob\FileGlob.cs:line 29
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.DocAsCode.GlobUtility.ExpandFileMapping(String baseDirectory, FileMapping fileMapping) in C:\projects\GitHub\docfx\src\docfx\Glob\GlobUtility.cs:line 31
   at Microsoft.DocAsCode.SubCommands.MetadataCommand.ConvertToInputModel(MetadataJsonItemConfig configModel) in C:\projects\GitHub\docfx\src\docfx\SubCommands\MetadataCommand.cs:line 93
   at Microsoft.DocAsCode.SubCommands.MetadataCommand.<GetInputModels>d__11.MoveNext() in C:\projects\GitHub\docfx\src\docfx\SubCommands\MetadataCommand.cs:line 84
   at Microsoft.DocAsCode.SubCommands.MetadataCommand.Exec(SubCommandRunningContext context) in C:\projects\GitHub\docfx\src\docfx\SubCommands\MetadataCommand.cs:line 34
   at Microsoft.DocAsCode.SubCommands.CompositeCommand.Exec(SubCommandRunningContext context) in C:\projects\GitHub\docfx\src\docfx\SubCommands\CompositeCommand.cs:line 38
   at Microsoft.DocAsCode.Program.ExecSubCommand(String[] args) in C:\projects\GitHub\docfx\src\docfx\Program.cs:line 75
	0 Warning(s)
	1 Error(s)
```

**Comment by superyyrrzz** [comment]
Hi @Eonasdan , if the folder you want to exclude isn't located in the doc's root path, you should use `"exclude": ["**/node_modules/", "**/bower_components/"]`

**Comment by Eonasdan** [comment]
Still didn't work. I uploaded a [sample project](http://eonasdan.com/files/doxfxtest.7z). I removed the node and packages folder to keep the zip light weight so you'll need to restore  those of course.

**Comment by superyyrrzz** [comment]
@Eonasdan It's caused by some deep nested package like `doxfxtest.MVC\node_modules\grunt-bower-task\node_modules\bower\node_modules\update-notifier\node_modules\latest-version\node_modules\package-json\node_modules\registry-url\node_modules\npmconf\node_modules\config-chain\node_modules\proto-list`, and it works for me to add `"**/node_modules/"` like below:
```json
"metadata": [
    {
        "src": [
            {
                "files": [ "**.sln" ],
                "exclude": [
                    "**/obj/**",
                    "**/bin/**",
                    "site/**",
                    "**/node_modules/"
                ]
            }
        ],
        "dest": "obj/api"
    }
  ],
```

**Comment by Eonasdan** [comment]
image

I think that managed to be the one node I didn't try for some reason. Go figure. Works with both my test project and my clients project :+1: when do you think this will go into release?

**Comment by superyyrrzz** [comment]
Next Monday, in DocFX 1.9 :smiley:

**Pull request closed without merging**
