### PR TITLE
disable anchorjs as it fails when title contains '<' and '>'

### PR DESCRIPTION
**Pull request by superyyrrzz**
#1191 
e.g. http://dotnet.github.io/docfx/api/Microsoft.DocAsCode.Build.Common.BaseModelAttributeHandler-1.html

### CODE REVIEW

**Comment by pascalberger** [comment]
@superyyrrzz Is there an upstream issue created for AnchorJS which can be tracked?

**Comment by superyyrrzz** [comment]
@pascalberger Seems the bug lies in jQuery, not anchorjs. We are still investigating it.

**Comment by superyyrrzz** [comment]
root cause is #1331

**Comment by superyyrrzz** [comment]
@pascalberger The PR resolving this has been merged by anchorjs: bryanbraun/anchorjs#81. We'll add it back when anchorjs' new version is released.

**Pull request merged**
