### PR TITLE
Add NonDNX.sln

### PR DESCRIPTION
**Pull request by qinezh**

### CODE REVIEW

**Comment by vwxyzh** [comment]
what about add new config `NonDnxDebug` and `NonDnxRelease` in `all.sln`?

**Comment by qinezh** [comment]
Add an extra solution for non-DNX seems more clear since it no need load DNX projects?

**Comment by hellosnow** [comment]
:shipit:

**Comment by ansyral** [comment]
:+1:

**Comment by chenkennt** [comment]
:shipit:

**Pull request merged**
