### PR TITLE
dispose file cache in dfm include.

### PR DESCRIPTION
**Pull request by vwxyzh**
@ansyral

### CODE REVIEW

**Comment by ansyral** [comment]
>                     }

if MarkdownService != null we should clean it up?

---
Refers to: src/Microsoft.DocAsCode.Build.Engine/SingleDocumentBuilder.cs:154 in b7bf0c3. [](commit_id = b7bf0c368708c18bbbd7cfaafdb22ce39baf2cde, deletion_comment = False)

**Comment by hellosnow** [comment]
:shipit:

**Comment by vwxyzh** [comment]
>                     }

no, leave it to dispose.

---
In reply to: [269728006](https://github.com/dotnet/docfx/pull/1089#issuecomment-269728006) [](ancestors = 269728006)

---
Refers to: src/Microsoft.DocAsCode.Build.Engine/SingleDocumentBuilder.cs:154 in b7bf0c3. [](commit_id = b7bf0c368708c18bbbd7cfaafdb22ce39baf2cde, deletion_comment = False)

**Comment by ansyral** [comment]
>                     }

not noticed the dispose method below

---
In reply to: [269733672](https://github.com/dotnet/docfx/pull/1089#issuecomment-269733672) [](ancestors = 269733672,269728006)

---
Refers to: src/Microsoft.DocAsCode.Build.Engine/SingleDocumentBuilder.cs:154 in b7bf0c3. [](commit_id = b7bf0c368708c18bbbd7cfaafdb22ce39baf2cde, deletion_comment = False)

**Comment by ansyral** [comment]
:shipit:

**Pull request merged**
