### PR TITLE
Consume locale from op config

### PR DESCRIPTION
**Pull request by live1206**
[work item](https://dev.azure.com/ceapex/Engineering/_workitems/edit/150975?src=WorkItemMention&src-action=artifact_link)

[op config example](https://github.com/MicrosoftDocs/mc-local-pr/blob/master/.openpublishing.publish.config.json#L7)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/docfx/pull/5483)

### CODE REVIEW

**Comment by yufeih** [comment]
I was wondering why locale is calculated differently between `mc-local-pr` and `mc-docs-pr`. For `mc-docs-pr`, it is published to `DocsAzureCN` and the default locale for that site is `zh-cn`. I suppose `mc-local-pr` is also published to `DocsAzureCN`

**Comment by live1206** [comment]
> I was wondering why locale is calculated differently between `mc-local-pr` and `mc-docs-pr`. For `mc-docs-pr`, it is published to `DocsAzureCN` and the default locale for that site is `zh-cn`. I suppose `mc-local-pr` is also published to `DocsAzureCN`

@fenxu Could you help answer this question?

**Comment by fenxu** [comment]
> 
> 
> > I was wondering why locale is calculated differently between `mc-local-pr` and `mc-docs-pr`. For `mc-docs-pr`, it is published to `DocsAzureCN` and the default locale for that site is `zh-cn`. I suppose `mc-local-pr` is also published to `DocsAzureCN`
> 
> @fenxu Could you help answer this question?

I'll doing a check for all PROD data. However, service side logic never gurrantee the URL format for localization.

**Comment by live1206** [comment]
These are LOC repositories not following v3 naming convention:
https://mseng.visualstudio.com/Documentation/_git/O365API_zh-tw
https://mseng.visualstudio.com/Documentation/_git/O365API_zh-cn
https://mseng.visualstudio.com/Documentation/_git/O365API_ru-ru
https://mseng.visualstudio.com/Documentation/_git/O365API_pt-br
https://mseng.visualstudio.com/Documentation/_git/O365API_ja-jp
https://mseng.visualstudio.com/Documentation/_git/O365API_fr-fr
https://mseng.visualstudio.com/Documentation/_git/O365API_es-es
https://mseng.visualstudio.com/Documentation/_git/O365API_de-de
https://github.com/MicrosoftDocs/CommunityDocs-zh-tw
https://github.com/MicrosoftDocs/CommunityDocs-zh-cn
https://github.com/MicrosoftDocs/CommunityDocs-ru-ru
https://github.com/MicrosoftDocs/CommunityDocs-pt-br
https://github.com/MicrosoftDocs/CommunityDocs-ko-kr
https://github.com/MicrosoftDocs/CommunityDocs-ja-jp
https://github.com/MicrosoftDocs/CommunityDocs-it-it
https://github.com/MicrosoftDocs/CommunityDocs-fr-fr
https://github.com/MicrosoftDocs/CommunityDocs-es-es
https://github.com/MicrosoftDocs/CommunityDocs-de-de
https://github.com/MicrosoftDocs/mc-local-pr

We will postpone these repositories for v3 migration.

**Comment by live1206** [comment]
close this PR for now, there is a work item tracking this

**Pull request closed without merging**
