### PR TITLE
fix: replace unresolved crefs with the cref-value instead of just rem…

### LINKED ISSUE #7245: triple-slash links to .NET base libraries erase output
**Operating System**: Windows

**DocFX Version Used**: 2.56.7.0

**Template used**: `default`

## Steps to Reproduce
Here's a minimal repro: [docfx-issue.zip](https://github.com/dotnet/docfx/files/6225724/docfx-issue.zip)

1. In C# code, add /// comments that reference a BCL class, such as System.Exception.
2. Add all relevant `using` lines.
2. In docfx.json, set xrefService to `https://xref.docs.microsoft.com/query?uid={uid}`
2. Run docfx

## Expected Behavior
Ideally, docfx should use the xrefService to make a link. At minimum, though, it should show the original text.

## Actual Behavior
docfx fails to resolve the links, and *the text does not appear*.

## Details

The C# from the repro:
```
using System;
using System.Threading.Tasks;
namespace Testing
{
	public class Class1 
	{ 
		/// <summary>
		/// Cref: <see cref="System.Threading.Tasks.Task"/>
		/// <br/>
		/// Xref: @System.Threading.Tasks.Task
		/// </summary>
		/// <exception cref="System.Exception">exception doc</exception>
		public void Foo()
		{
		}
	}
}
```

In the output, note that:
* The xref resolved correctly, which shows that docfx can resolve the reference and that `xrefService` is configured correctly. 
* For the cref, the text is missing. At minimum, it should say System.Threading.Tasks.Task even if it's not a link.
* The exception documentation is missing entirely.
2021-03-29 21_12_31-Class Class1

These are the warnings:
```
[21-03-30 02:09:08.783]Warning:[MetadataCommand.ExtractMetadata]Invalid cref value "!:System.Threading.Tasks.Task" found in triple-slash-comments for Foo defined in C:\Users\3mave\source\tests\docfx-issue\src\Class1.cs Line 12, ignored.
[21-03-30 02:09:08.786]Warning:[MetadataCommand.ExtractMetadata]Invalid cref value "!:System.Exception" found in triple-slash-comments for Foo defined in C:\Users\3mave\source\tests\docfx-issue\src\Class1.cs Line 12, ignored.
```

### PR DESCRIPTION
**Pull request by Algorithman**
…oving them

fixes #7245

### CODE REVIEW

**Comment by Emdot** [comment]
@herohua: The issue is the only thing keeping me from adopting docfx, and this fix looks like an easy win. Could we get a review, please?

**Review by superyyrrzz — APPROVED** [review]

**Comment by superyyrrzz** [comment]
@Algorithman @Emdot  Sorry for the terrible late review... The change looks good. Thanks for contribution!

**Comment by ericmutta** [comment]
Hello @superyyrrzz was this fix ever shipped with DocFX? We are facing the [same problem](https://github.com/npgsql/doc/issues/243) in the npgsql repo. All `cref` pointers to classes in the BCL do NOT render any output and I wanted exactly what this fix provides: to render the unresolved reference as text instead of just removing it entirely.

**Comment by GlitchedPolygons** [comment]
Same problem here with my Unity package docs: 

image

**Pull request merged**
